[GitHub] Update to 1.1.4-a937c40b238be216f274ad4de79f6216 from 1.1.4-5f0efa5b768ca4017b3104dc35554b9b Detected Schema changes:
```
├──[➖] webhooks (63135:5)❌
├──[➖] webhooks (63069:5)❌
├──[➖] webhooks (63201:5)❌
├──[➖] webhooks (63003:5)❌
├─┬Paths
│ └─┬/advisories
│   └─┬GET
│     ├──[➖] parameters (234:15)❌
│     ├──[➖] parameters (241:15)❌
│     └─┬Responses
│       └─┬200
│         └─┬application/json
│           └─┬default
│             └──[🔀] value (196188:7)
└─┬Components
  ├──[➖] schemas (190204:7)❌
  ├──[➖] schemas (190134:7)❌
  ├──[➖] schemas (190099:7)❌
  ├──[➖] schemas (190169:7)❌
  ├─┬api-overview
  │ └─┬domains
  │   └──[➖] properties (70016:13)❌
  └─┬global-advisory
    └──[➖] properties (64758:9)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 3             | 2                |
| components       | 6             | 6                |

Date: 08/27/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _8_ out of _9_
- **Modifications**: _1_
- **Removals**: _12_
- **Breaking Removals**: _12_

ERROR: breaking changes discovered