[GitHub] Update to 1.1.4-7714c88ff6c09a4c649c225f5b2ccf5c from 1.1.4-736baa369515112b9bfb0e87033d2fcb Detected Schema changes:
```
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         ├──[🔀] value (219603:9)
│ │ │         ├──[🔀] value (219603:9)
│ │ │         ├──[🔀] value (219603:9)
│ │ │         ├──[🔀] value (219603:9)
│ │ │         ├──[🔀] value (219603:9)
│ │ │         ├──[🔀] value (219603:9)
│ │ │         ├──[🔀] value (219603:9)
│ │ │         ├──[🔀] value (219603:9)
│ │ │         ├──[🔀] value (219603:9)
│ │ │         ├──[🔀] value (219603:9)
│ │ │         ├──[🔀] value (219603:9)
│ │ │         ├──[🔀] value (219603:9)
│ │ │         ├──[🔀] value (219603:9)
│ │ │         ├──[➖] value (219755:9)
│ │ │         ├──[➖] value (219755:9)
│ │ │         └──[➖] value (219755:9)
│ │ └─┬PATCH
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[🔀] value (219624:9)
│ │           ├──[🔀] value (219624:9)
│ │           ├──[🔀] value (219624:9)
│ │           ├──[🔀] value (219624:9)
│ │           ├──[🔀] value (219624:9)
│ │           ├──[🔀] value (219624:9)
│ │           ├──[🔀] value (219624:9)
│ │           ├──[🔀] value (219624:9)
│ │           ├──[🔀] value (219624:9)
│ │           ├──[🔀] value (219624:9)
│ │           ├──[🔀] value (219624:9)
│ │           ├──[🔀] value (219624:9)
│ │           ├──[🔀] value (219624:9)
│ │           ├──[➖] value (219779:9)
│ │           ├──[➖] value (219779:9)
│ │           └──[➖] value (219779:9)
│ ├─┬/orgs/{org}/secret-scanning/alerts
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (201859:7)
│ ├─┬/orgs/{org}/properties/schema/{custom_property_name}
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         ├──[🔀] value (206840:9)
│ │ │         ├──[🔀] value (206840:9)
│ │ │         └──[➖] value (206967:9)
│ │ └─┬PUT
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[🔀] value (206840:9)
│ │           ├──[🔀] value (206840:9)
│ │           └──[➖] value (206967:9)
│ ├─┬/repos/{owner}/{repo}/secret-scanning/alerts
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (219527:7)
│ ├─┬/enterprises/{enterprise}/secret-scanning/alerts
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (201859:7)
│ ├─┬/repos/{owner}/{repo}/releases/assets/{asset_id}
│ │ └─┬GET
│ │   └──[🔀] description (37787:20)
│ ├─┬/orgs/{org}/properties/schema
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         └──[🔀] value (206821:7)
│ │ └─┬PATCH
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (206821:7)
│ └─┬/app/installations/{installation_id}/access_tokens
│   └─┬POST
│     └──[🔀] description (727:20)
└─┬Components
  ├─┬team-role-assignment
  │ └──[➖] properties (74643:9)❌
  ├─┬secret-scanning-alert
  │ ├──[➖] properties (88852:9)❌
  │ ├──[➖] properties (88857:9)❌
  │ └──[➖] properties (88848:9)❌
  ├─┬organization-secret-scanning-alert
  │ ├──[➖] properties (70064:9)❌
  │ ├──[➖] properties (70069:9)❌
  │ └──[➖] properties (70060:9)❌
  ├─┬secret-scanning-alert-webhook
  │ ├──[➖] properties (101337:9)❌
  │ ├──[➖] properties (101342:9)❌
  │ └──[➖] properties (101333:9)❌
  ├─┬user-role-assignment
  │ ├──[➖] properties (74724:9)❌
  │ └──[➖] properties (74734:9)❌
  ├─┬organization-role
  │ ├──[➖] properties (74592:9)❌
  │ └──[➖] properties (74604:9)❌
  └─┬custom-property
    └──[➖] properties (75221:9)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 45            | 0                |
| components       | 15            | 15               |

Date: 11/13/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _15_ out of _60_
- **Modifications**: _37_
- **Removals**: _23_
- **Breaking Removals**: _15_

ERROR: breaking changes discovered