[GitHub] Update to 1.1.4-0060b499a5d39e935a73965cb74e1cd7 from 1.1.4-b8769452718d6d7793dc313b1b4aae02 Detected Schema changes:
```
├─┬Paths
│ ├─┬/gists/{gist_id}
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         └──[🔀] value (202202:9)
│ │ └─┬PATCH
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬updateGist
│ │           └──[🔀] value (202202:9)
│ ├─┬/enterprises/{enterprise}/copilot/usage
│ │ └─┬GET
│ │   └──[🔀] description (1583:20)
│ ├─┬/repos/{owner}/{repo}/dependency-graph/sbom
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (214770:9)
│ ├─┬/gists/{gist_id}/{sha}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (202202:9)
│ └─┬/gists
│   └─┬POST
│     └─┬Responses
│       └─┬201
│         └─┬application/json
│           └─┬default
│             └──[🔀] value (202202:9)
└─┬Components
  ├──[➖] schemas (76181:7)❌
  ├─┬gist-simple
  │ └─┬files
  │   └─┬Schema
  │     └──[➖] properties (71175:15)❌
  ├─┬dependency-graph-spdx-sbom
  │ └─┬sbom
  │   ├──[➕] required (84250:13)❌
  │   ├──[➖] properties (84146:13)❌
  │   ├──[➖] properties (84279:13)❌
  │   ├─┬documentNamespace
  │   │ └──[🔀] examples (84148:17)
  │   └─┬packages
  │     ├──[➕] required (84243:17)❌
  │     └─┬Schema
  │       └─┬name
  │         └──[🔀] examples (84163:23)
  └─┬base-gist
    └─┬files
      └─┬Schema
        └──[➖] properties (70757:15)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| components       | 9             | 7                |
| paths            | 6             | 0                |

Date: 11/06/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _7_ out of _15_
- **Modifications**: _8_
- **Removals**: _5_
- **Additions**: _2_
- **Breaking Removals**: _5_
- **Breaking Additions**: _2_

ERROR: breaking changes discovered