[GitHub] Update to 1.1.4-f8cf9b6b12b5036930560db0c2532fe8 from 1.1.4-8d294609e3486ce785da733055f6fa7b Detected Schema changes:
├─┬Paths
│ └─┬/orgs/{org}/repos
│   └─┬POST
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └─┬custom_properties
│             └──[M] description (10854:32)
└─┬Components
  └─┬code-scanning-default-setup-update
    ├──[-] additionalProperties (75575:29)❌
    ├──[+] required (75577:9)❌
    └─┬state
      └──[M] description (75550:24)

Date: 11/11/23 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 1             | 0
components       | 3             | 2

❌  2 Breaking changes out of 4
INFO: Modifications: 2
INFO: Removals: 1
INFO: Additions: 1
INFO: Breaking Removals: 1
INFO: Breaking Additions: 1

ERROR: breaking changes discovered