[GitHub] Update to 1.1.4-736baa369515112b9bfb0e87033d2fcb from 1.1.4-0060b499a5d39e935a73965cb74e1cd7 Detected Schema changes:
```
└─┬Components
  └─┬enterprise-team
    └─┬group_id
      ├──[🔀] examples (68838:13)
      └──[🔀] type (68835:11)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| components       | 2             | 1                |

Date: 11/07/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _1_ out of _2_
- **Modifications**: _2_
- **Breaking Modifications**: _1_

ERROR: breaking changes discovered