[GitHub] Update to 1.1.4 (hash: 6d83cf0b9aff678c7dd09cd04153b933) from 1.1.4 (hash: fb7b9b9f4a829c9a2a2c39dbb35d66f0) Detected Schema changes:
├─┬Paths
│ ├──[-] path (280:3)❌
│ ├──[-] path (5832:3)❌
│ ├──[-] path (5765:3)❌
│ ├──[-] path (117:3)❌
│ ├──[+] path (5639:3)
│ ├──[+] path (5572:3)
│ └─┬/repos/{owner}/{repo}/pulls/{pull_number}/comments
│   └─┬POST
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └─┬subject_type
│             ├──[+] enum (31484:21)
│             ├──[+] enum (31485:21)
│             ├──[-] enum (31677:21)❌
│             └──[-] enum (31678:21)❌
└─┬Components
  ├──[-] examples (202832:7)❌
  ├──[-] examples (202893:7)❌
  ├──[-] schemas (84301:7)❌
  ├──[-] schemas (59673:7)❌
  ├──[-] schemas (84314:7)❌
  ├─┬webhook-secret-scanning-alert-reopened
  │ └─┬alert
  │   └──[M] $ref (79983:13)❌
  ├─┬webhook-secret-scanning-alert-created
  │ └─┬alert
  │   └──[M] $ref (79983:13)❌
  ├─┬webhook-secret-scanning-alert-revoked
  │ └─┬alert
  │   └──[M] $ref (79983:13)❌
  ├─┬webhook-secret-scanning-alert-location-created
  │ └─┬alert
  │   └──[M] $ref (79983:13)❌
  ├─┬code-scanning-default-setup-update
  │ └─┬languages
  │   └──[M] description (72736:24)
  └─┬webhook-secret-scanning-alert-resolved
    └─┬alert
      └──[M] $ref (191706:11)❌

Date: 07/29/23 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 10            | 6
components       | 11            | 10
❌  16 Breaking changes out of 21
INFO: Modifications: 6
INFO: Removals: 11
INFO: Additions: 4
INFO: Breaking Removals: 11
INFO: Breaking Modifications: 5

ERROR: breaking changes discovered