[GitHub] Update to 1.1.4-846e79a967c97fff1f751d713e16fc13 from 1.1.4-a62519fb7f7e65d753064fbb86d95c90 Detected Schema changes:
```
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/contents/{path}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬Schema
│ │           └──[➖] discriminator (25962:19)❌
│ ├─┬/repos/{owner}/{repo}/check-runs
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └──[➖] discriminator (22078:17)❌
│ ├─┬/repos/{owner}/{repo}/branches/{branch}/protection/restrictions/users
│ │ ├─┬PUT
│ │ │ └─┬Requestbody
│ │ │   ├──[🔀] required (21701:19)❌
│ │ │   └─┬application/json
│ │ │     └─┬Schema
│ │ │       ├──[➖] required (21698:17)❌
│ │ │       ├──[➖] type (21690:21)❌
│ │ │       ├──[➖] example (21700:17)
│ │ │       ├──[➖] properties (21692:17)❌
│ │ │       ├──[➕] oneOf (21718:17)
│ │ │       └──[➕] oneOf (21706:17)
│ │ ├─┬POST
│ │ │ └─┬Requestbody
│ │ │   ├──[🔀] required (21634:19)❌
│ │ │   └─┬application/json
│ │ │     └─┬Schema
│ │ │       ├──[➖] required (21635:17)❌
│ │ │       ├──[➖] type (21627:21)❌
│ │ │       ├──[➖] example (21637:17)
│ │ │       ├──[➖] properties (21629:17)❌
│ │ │       ├──[➕] oneOf (21651:17)
│ │ │       └──[➕] oneOf (21639:17)
│ │ └─┬DELETE
│ │   └─┬Requestbody
│ │     ├──[➖] required (21749:19)❌
│ │     └─┬application/json
│ │       └─┬Schema
│ │         ├──[➖] required (21761:17)❌
│ │         ├──[➖] type (21753:21)❌
│ │         ├──[➖] example (21763:17)
│ │         ├──[➖] properties (21755:17)❌
│ │         ├──[➕] oneOf (21784:17)
│ │         └──[➕] oneOf (21772:17)
│ └─┬/repos/{owner}/{repo}/branches/{branch}/protection/restrictions/apps
│   ├─┬PUT
│   │ └─┬Requestbody
│   │   ├──[🔀] required (21240:19)❌
│   │   └─┬application/json
│   │     └─┬Schema
│   │       ├──[➖] required (21250:17)❌
│   │       ├──[➖] type (21240:21)❌
│   │       ├──[➖] example (21252:17)
│   │       ├──[➖] properties (21242:17)❌
│   │       ├──[➕] oneOf (21245:17)
│   │       └──[➕] oneOf (21259:17)
│   ├─┬POST
│   │ └─┬Requestbody
│   │   ├──[🔀] required (21176:19)❌
│   │   └─┬application/json
│   │     └─┬Schema
│   │       ├──[➖] required (21190:17)❌
│   │       ├──[➖] type (21180:21)❌
│   │       ├──[➖] example (21192:17)
│   │       ├──[➖] properties (21182:17)❌
│   │       ├──[➕] oneOf (21181:17)
│   │       └──[➕] oneOf (21195:17)
│   └─┬DELETE
│     └─┬Requestbody
│       ├──[➖] required (21296:19)❌
│       └─┬application/json
│         └─┬Schema
│           ├──[➖] required (21310:17)❌
│           ├──[➖] type (21300:21)❌
│           ├──[➖] example (21312:17)
│           ├──[➖] properties (21302:17)❌
│           ├──[➕] oneOf (21308:17)
│           └──[➕] oneOf (21322:17)
└─┬Components
  └─┬copilot-seat-details
    ├─┬organization
    │ ├──[➕] type (67542:11)❌
    │ ├──[➕] description (67544:24)
    │ ├──[➖] anyOf (67525:13)❌
    │ ├──[➖] anyOf (67243:7)❌
    │ └──[➕] oneOf (67256:7)
    └─┬assignee
      └──[🔀] $ref (67535:11)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 44            | 26               |
| components       | 6             | 4                |

Date: 10/01/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _30_ out of _50_
- **Modifications**: _5_
- **Removals**: _30_
- **Additions**: _15_
- **Breaking Removals**: _24_
- **Breaking Modifications**: _5_
- **Breaking Additions**: _1_

ERROR: breaking changes discovered