[GitHub] Update to 1.1.4-cdf06887872e14c33e252a1a6bb7b705 from 1.1.4-3a65313f38dc50db9634434686a9f27d Detected Schema changes:
├──Paths
└─┬Components
  └─┬copilot-seat-details
    └─┬assignee
      ├──[+] enum (67461:13)
      ├──[-] oneOf (67318:7)❌
      ├──[-] oneOf (59853:7)❌
      └──[-] oneOf (67246:7)❌

Date: 09/27/23 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 0             | 0
components       | 4             | 3
❌  3 Breaking changes out of 4
INFO: Removals: 3
INFO: Additions: 1
INFO: Breaking Removals: 3

ERROR: breaking changes discovered