[GitHub] Update to 1.1.4-3a65313f38dc50db9634434686a9f27d from 1.1.4-89e57817e371230a5fc9246a770d5064 Detected Schema changes:
├─┬Paths
│ ├──[-] path (15953:3)❌
│ ├─┬/repos/{owner}/{repo}/environments
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (222532:9)
│ ├─┬/repos/{owner}/{repo}/check-runs/{check_run_id}
│ │ └─┬PATCH
│ │   └──[M] description (19741:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/{runner_id}
│ │ ├─┬GET
│ │ │ └──[M] description (15273:20)
│ │ └─┬DELETE
│ │   └──[M] description (15307:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}/deliveries/{delivery_id}/attempts
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (233622:20)
│ ├─┬/repos/{owner}/{repo}/check-suites/{check_suite_id}/check-runs
│ │ └─┬GET
│ │   └──[M] description (20245:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (233622:20)
│ ├─┬/repos/{owner}/{repo}/commits/{ref}/check-suites
│ │ └─┬GET
│ │   └──[M] description (22780:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/registration-token
│ │ └─┬POST
│ │   └──[M] description (15193:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/{runner_id}/labels/{name}
│ │ └─┬DELETE
│ │   └──[M] description (15503:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/generate-jitconfig
│ │ └─┬POST
│ │   └──[M] description (15121:20)
│ ├─┬/repos/{owner}/{repo}/actions/variables/{name}
│ │ ├─┬GET
│ │ │ └──[M] description (16624:20)
│ │ ├─┬DELETE
│ │ │ └──[M] description (16703:20)
│ │ └─┬PATCH
│ │   └──[M] description (16658:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries/{delivery_id}
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (233622:20)
│ ├─┬/repos/{owner}/{repo}/actions/jobs/{job_id}/rerun
│ │ └─┬POST
│ │   └──[M] description (14506:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}/config
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (233622:20)
│ │ └─┬PATCH
│ │   └─┬Parameters
│ │     └──[M] description (233622:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/pings
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (233622:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}/deliveries/{delivery_id}
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (233622:20)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/variables
│ │ ├─┬GET
│ │ │ └──[M] description (35766:20)
│ │ └─┬POST
│ │   └──[M] description (35814:20)
│ ├─┬/repos/{owner}/{repo}/actions/variables
│ │ ├─┬GET
│ │ │ └──[M] description (16522:20)
│ │ └─┬POST
│ │   └──[M] description (16569:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries/{delivery_id}/attempts
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (233622:20)
│ ├─┬/repos/{owner}/{repo}/commits/{ref}/check-runs
│ │ └─┬GET
│ │   └──[M] description (22715:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/config
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (233622:20)
│ │ └─┬PATCH
│ │   └─┬Parameters
│ │     └──[M] description (233622:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/tests
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (233622:20)
│ ├─┬/repos/{owner}/{repo}/actions/organization-variables
│ │ └─┬GET
│ │   └──[M] description (14706:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/remove-token
│ │ └─┬POST
│ │   └──[M] description (15231:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (233622:20)
│ │ ├─┬DELETE
│ │ │ └─┬Parameters
│ │ │   └──[M] description (233622:20)
│ │ └─┬PATCH
│ │   └─┬Parameters
│ │     └──[M] description (233622:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners
│ │ └─┬GET
│ │   └──[M] description (15031:20)
│ ├─┬/repos/{owner}/{repo}/community/profile
│ │ └─┬GET
│ │   └──[M] description (22917:20)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/variables/{name}
│ │ ├─┬GET
│ │ │ └──[M] description (35869:20)
│ │ ├─┬DELETE
│ │ │ └──[M] description (35948:20)
│ │ └─┬PATCH
│ │   └──[M] description (35903:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}/deliveries
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (233622:20)
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         └──[M] value (222593:9)
│ │ └─┬PUT
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (222593:9)
│ ├─┬/repos/{owner}/{repo}/actions/runs/{run_id}/cancel
│ │ └─┬POST
│ │   └──[M] description (15887:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/downloads
│ │ └─┬GET
│ │   └──[M] description (15085:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (233622:20)
│ │ ├─┬DELETE
│ │ │ └─┬Parameters
│ │ │   └──[M] description (233622:20)
│ │ └─┬PATCH
│ │   └─┬Parameters
│ │     └──[M] description (233622:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}/pings
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (233622:20)
│ └─┬/repos/{owner}/{repo}/actions/runners/{runner_id}/labels
│   ├─┬GET
│   │ └──[M] description (15335:20)
│   ├─┬PUT
│   │ └──[M] description (15417:20)
│   ├─┬POST
│   │ └──[M] description (15364:20)
│   └─┬DELETE
│     └──[M] description (15472:20)
└─┬Components
  ├─┬repository-rule-required-deployments
  │ └──[M] description (68442:20)
  ├─┬repository-rule-non-fast-forward
  │ └──[M] description (68563:20)
  ├─┬environment
  │ └─┬protection_rules
  │   └─┬Schema
  │     └─┬ANYOF
  │       └──[-] properties (76789:17)❌
  ├─┬repository-rule-required-signatures
  │ └──[M] description (68465:20)
  ├─┬repository-rule-required-linear-history
  │ └──[M] description (68431:20)
  └─┬repository-rule-required-status-checks
    └──[M] description (68533:20)

Date: 09/26/23 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 53            | 1
components       | 6             | 1
❌  2 Breaking changes out of 59
INFO: Modifications: 57
INFO: Removals: 2
INFO: Breaking Removals: 2

ERROR: breaking changes discovered