[GitHub] Update to 1.1.4-30445c941a97be3bcb4ba3b3bae9e8f3 from 1.1.4-165dc4edaf3899f8fa74f18ab70adbb6 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 9d03d1
```
                                                                                └─┬Tags
  └──[➖] code-security (92:3)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| tags             | 1             | 1                |

Date: 06/04/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _1_ out of _1_
- **Removals**: _1_
- **Breaking Removals**: _1_

                                                                                SPEC: extracted 2 commits from history
ERROR: breaking changes discovered