[GitHub] Update to 1.1.4-9737a21f44d34768b2b336a00c312699 from 1.1.4-9fb2901e192ade3e8ccc32f59e517598 Detected Schema changes:
```
├─┬Paths
│ ├──[➖] path (39159:3)❌
│ ├─┬/repos/{owner}/{repo}/git/commits/{commit_sha}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (215666:9)
│ ├─┬/repos/{owner}/{repo}/actions/runs
│ │ └─┬GET
│ │   └──[🔀] description (19054:20)
│ ├─┬/repos/{owner}/{repo}/actions/workflows/{workflow_id}/runs
│ │ └─┬GET
│ │   └──[🔀] description (20488:20)
│ ├─┬/orgs/{org}/rulesets/rule-suites
│ │ └─┬GET
│ │   └─┬Parameters
│ │     ├──[🔀] description (226468:20)
│ │     └─┬Schema
│ │       └──[🔀] type (226472:15)❌
│ ├─┬/repos/{owner}/{repo}/contents/{path}
│ │ ├─┬PUT
│ │ │ └─┬Responses
│ │ │   ├─┬200
│ │ │   │ └─┬application/json
│ │ │   │   └─┬example-for-updating-a-file
│ │ │   │     └──[🔀] value (214513:9)
│ │ │   └─┬201
│ │ │     └─┬application/json
│ │ │       └─┬example-for-creating-a-file
│ │ │         └──[🔀] value (214555:9)
│ │ └─┬DELETE
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (214597:9)
│ └─┬/repos/{owner}/{repo}/git/commits
│   └─┬POST
│     └─┬Responses
│       └─┬201
│         └─┬application/json
│           └─┬default
│             └──[🔀] value (215639:9)
└─┬Components
  ├──[➖] examples (220100:7)❌
  ├──[➖] schemas (89349:7)❌
  ├──[➖] schemas (89371:7)❌
  ├─┬webhook-status
  │ └─┬commit
  │   └─┬commit
  │     └─┬verification
  │       └──[➖] properties (192128:21)❌
  ├─┬git-commit
  │ └─┬verification
  │   └──[➖] properties (85255:13)❌
  ├─┬verification
  │ └──[➖] properties (80845:9)❌
  ├─┬file-commit
  │ └─┬commit
  │   └─┬verification
  │     └──[➖] properties (84032:17)❌
  └─┬timeline-committed-event
    └─┬verification
      └──[➖] properties (86942:13)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 10            | 2                |
| components       | 8             | 8                |

Date: 11/27/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _10_ out of _18_
- **Modifications**: _9_
- **Removals**: _9_
- **Breaking Removals**: _9_
- **Breaking Modifications**: _1_

ERROR: breaking changes discovered