[GitHub] Update to 1.1.4-1f428455b4cea06755dbb12f469fc171 from 1.1.4-64034f0aaa76d6090b5eb70ffe778e12 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 42be64
                                                                                SPEC: extracted 2 commits from history

```
└─┬Components
  ├─┬webhook-custom-property-updated
  │ └──[➕] required (103944:9)❌
  ├─┬webhook-custom-property-deleted
  │ └──[➕] required (103922:9)❌
  └─┬webhook-custom-property-created
    └──[➕] required (103894:9)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| components       | 3             | 3                |

Date: 07/27/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _3_ out of _3_
- **Additions**: _3_
- **Breaking Additions**: _3_

ERROR: breaking changes discovered