[GitHub] Update to 1.1.4-3fc5da0b62540a45f2138abebf230a76 from 1.1.4-b76fea2cb5ac476be8636e4403ed63dc Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit baaf72
```
                                                                                SPEC: extracted 2 commits from history
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └──[➖] codes (237737:7)❌
│ └─┬/repos/{owner}/{repo}/actions/runs
│   └─┬GET
│     └──[🔀] description (16758:20)
└─┬Components
  └──[➖] responses (237737:7)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 2             | 1                |
| components       | 1             | 1                |

Date: 03/26/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _3_
- **Modifications**: _1_
- **Removals**: _2_
- **Breaking Removals**: _2_

ERROR: breaking changes discovered