[GitHub] Update to 1.1.4-864f215bcb7fda8ed79c1295fb5a81d2 from 1.1.4-7d381dcec5cc31f738fdd8a803bade45 Detected Schema changes:
```
├─┬Paths
│ ├─┬/enterprises/{enterprise}/secret-scanning/alerts
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[🔀] description (229928:20)
│ ├─┬/orgs/{org}/secret-scanning/alerts
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[🔀] description (229928:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}
│ │ └─┬PATCH
│ │   ├─┬Responses
│ │   │ └──[➖] codes (231210:7)❌
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       ├─┬Schema
│ │       │ └──[➖] properties (25950:17)❌
│ │       └─┬default
│ │         ├──[🔀] value (25955:19)
│ │         ├──[🔀] value (25955:19)
│ │         ├──[🔀] value (25955:19)
│ │         └──[➖] value (25957:19)
│ └─┬/repos/{owner}/{repo}/secret-scanning/alerts
│   └─┬GET
│     └─┬Parameters
│       └──[🔀] description (229928:20)
└─┬Components
  └──[➖] schemas (84954:7)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 9             | 2                |
| components       | 1             | 1                |

Date: 03/07/25 | Commit: Original: etc/specs/GitHub/current.spec.yaml, Modified: etc/specs/GitHub/previous.spec.yaml,

- ❌ **BREAKING Changes**: _3_ out of _10_
- **Modifications**: _6_
- **Removals**: _4_
- **Breaking Removals**: _3_

ERROR: breaking changes discovered