[GitHub] Update to 1.1.4-c3f89da8f4e736748f0a13e02db3c36d from 1.1.4-d2d01395df29a6b406754b59eca9b64e Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit fe2019
                                                                                SPEC: extracted 2 commits from history

```
├─┬Paths
│ ├─┬/orgs/{org}/organization-roles/{role_id}/users
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬Schema
│ │           └─┬Schema
│ │             └──[🔀] $ref (62615:14)❌
│ └─┬/orgs/{org}/organization-roles/{role_id}/teams
│   └─┬GET
│     └─┬Responses
│       └─┬200
│         └─┬application/json
│           └─┬Schema
│             └─┬Schema
│               └──[🔀] $ref (69923:14)❌
└─┬Components
  ├──[➖] schemas (94196:7)❌
  ├──[➖] schemas (70812:7)❌
  ├──[➖] schemas (94176:7)❌
  ├──[➖] schemas (70741:7)❌
  └─┬webhook-projects-v2-item-edited
    └─┬changes
      ├──[➖] description (129187:24)
      └─┬ONEOF
        └─┬field_value
          ├──[➖] properties (129200:19)❌
          ├──[➖] properties (129204:19)❌
          ├──[➖] properties (129202:19)❌
          └──[➖] properties (129215:19)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 2             | 2                |
| components       | 9             | 8                |

Date: 06/14/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _10_ out of _11_
- **Modifications**: _2_
- **Removals**: _9_
- **Breaking Removals**: _8_
- **Breaking Modifications**: _2_

ERROR: breaking changes discovered