[GitHub] Update to 1.1.4-a073e1a053477690d506f42cadb2ee51 from 1.1.4-dbba2c62a8f04380c590a1aa0d1194e8 Detected Schema changes:
```
├─┬Paths
│ ├─┬/orgs/{org}/teams/{team_slug}/projects/{project_id}
│ │ ├─┬GET
│ │ │ ├──[🔀] description (17404:20)
│ │ │ ├──[➖] deprecated (17439:19)
│ │ │ └─┬Extensions
│ │ │   └──[🔀] x-github (17432:9)
│ │ ├─┬PUT
│ │ │ ├──[🔀] description (17438:20)
│ │ │ ├──[➖] deprecated (17508:19)
│ │ │ └─┬Extensions
│ │ │   └──[🔀] x-github (17499:9)
│ │ └─┬DELETE
│ │   ├──[🔀] description (17505:20)
│ │   ├──[➖] deprecated (17535:19)
│ │   └─┬Extensions
│ │     └──[🔀] x-github (17524:9)
│ ├─┬/zen
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       ├──[➕] content (51145:15)
│ │       └──[➖] content (51142:15)❌
│ ├─┬/teams/{team_id}/projects/{project_id}
│ │ ├─┬GET
│ │ │ ├──[🔀] description (44885:20)
│ │ │ └─┬Extensions
│ │ │   └──[🔀] x-github (44912:9)
│ │ ├─┬PUT
│ │ │ ├──[🔀] description (44921:20)
│ │ │ └─┬Extensions
│ │ │   └──[🔀] x-github (44983:9)
│ │ └─┬DELETE
│ │   ├──[🔀] description (44992:20)
│ │   └─┬Extensions
│ │     └──[🔀] x-github (45014:9)
│ ├─┬/search/issues
│ │ └─┬GET
│ │   ├──[➖] parameters (230963:13)❌
│ │   ├──[🔀] description (43214:20)
│ │   ├──[➖] deprecated (43307:19)
│ │   └─┬Extensions
│ │     └──[🔀] x-github (43303:9)
│ ├─┬/orgs/{org}/teams/{team_slug}/projects
│ │ └─┬GET
│ │   ├──[🔀] description (17365:20)
│ │   ├──[➖] deprecated (17402:19)
│ │   └─┬Extensions
│ │     └──[🔀] x-github (17397:9)
│ ├─┬/repos/{owner}/{repo}/dependency-graph/compare/{basehead}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬403
│ │       └──[🔀] description (231263:20)
│ └─┬/teams/{team_id}/projects
│   └─┬GET
│     ├──[🔀] description (44842:20)
│     └─┬Extensions
│       └──[🔀] x-github (44875:9)
└─┬Components
  └──[➖] parameters (230963:7)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 27            | 2                |
| components       | 1             | 1                |

Date: 03/01/25 | Commit: Original: etc/specs/GitHub/current.spec.yaml, Modified: etc/specs/GitHub/previous.spec.yaml,

- ❌ **BREAKING Changes**: _3_ out of _28_
- **Modifications**: _19_
- **Removals**: _8_
- **Additions**: _1_
- **Breaking Removals**: _3_

ERROR: breaking changes discovered