[GitHub] Update to 1.1.4 (hash: fb7b9b9f4a829c9a2a2c39dbb35d66f0) from 1.1.4 (hash: 0f5f16d2e718bd17d7c5fec9099a3f35) Detected Schema changes:
├─┬Paths
│ ├──[-] path (16802:3)❌
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment-branch-policies/{branch_policy_id}
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (24476:14)
│ │ ├─┬PUT
│ │ │ └─┬External Docs
│ │ │   └──[M] url (24508:14)
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (24550:14)
│ ├─┬/repos/{owner}/{repo}/branches/{branch}/protection/restrictions/users
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (18655:14)
│ ├─┬/orgs/{org}/docker/conflicts
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (7056:14)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/secrets
│ │ └─┬GET
│ │   └──[M] description (35191:20)
│ ├─┬/repos/{owner}/{repo}/branches/{branch}/protection/restrictions/apps
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (18201:14)
│ ├─┬/repos/{owner}/{repo}/rulesets
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (33126:14)
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (33169:14)
│ ├─┬/repos/{owner}/{repo}/actions/workflows/{workflow_id}/runs
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (16554:14)
│ ├─┬/orgs/{org}/actions/variables
│ │ ├─┬GET
│ │ │ └──[M] description (4862:20)
│ │ └─┬POST
│ │   └──[M] description (4906:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/{runner_id}/labels
│ │ ├─┬GET
│ │ │ └──[M] description (14937:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (15015:20)
│ │ ├─┬POST
│ │ │ └──[M] description (14964:20)
│ │ └─┬DELETE
│ │   └──[M] description (15068:20)
│ ├─┬/repos/{owner}/{repo}/actions/secrets/public-key
│ │ └─┬GET
│ │   └──[M] description (15953:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/generate-jitconfig
│ │ └─┬POST
│ │   └──[M] description (14744:20)
│ ├─┬/projects/{project_id}/collaborators/{username}
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (13278:14)
│ ├─┬/repos/{owner}/{repo}/actions/permissions/selected-actions
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (14543:14)
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (14573:14)
│ ├─┬/orgs/{org}/codespaces
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (5441:14)
│ ├─┬/orgs/{org}/actions/runners
│ │ └─┬GET
│ │   └──[M] description (3966:20)
│ ├─┬/orgs/{org}/actions/variables/{name}/repositories
│ │ ├─┬GET
│ │ │ └──[M] description (5093:20)
│ │ └─┬PUT
│ │   └──[M] description (5139:20)
│ ├─┬/orgs/{org}/actions/secrets
│ │ └─┬GET
│ │   └──[M] description (4421:20)
│ ├─┬/repos/{owner}/{repo}/actions/runs/{run_id}/cancel
│ │ └─┬POST
│ │   └──[M] description (15478:20)
│ ├─┬/orgs/{org}/actions/secrets/public-key
│ │ └─┬GET
│ │   └──[M] description (4466:20)
│ ├─┬/users/{username}/packages/{package_type}/{package_name}/versions/{package_version_id}
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (43071:14)
│ ├─┬/orgs/{org}/codespaces/billing/selected_users
│ │ ├─┬POST
│ │ │ └─┬External Docs
│ │ │   └──[M] url (5563:14)
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (5621:14)
│ ├─┬/orgs/{org}/actions/runners/remove-token
│ │ └─┬POST
│ │   └──[M] description (4143:20)
│ ├─┬/user/packages/{package_type}/{package_name}/versions
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (41055:14)
│ ├─┬/orgs/{org}/members/{username}/copilot
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (8348:14)
│ ├─┬/
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (116:14)
│ ├─┬/repos/{owner}/{repo}/actions/organization-variables
│ │ └─┬GET
│ │   └──[M] description (14345:20)
│ ├─┬/orgs/{org}/codespaces/billing
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (5492:14)
│ ├─┬/orgs/{org}/actions/runners/{runner_id}/labels
│ │ ├─┬GET
│ │ │ └──[M] description (4236:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (4310:20)
│ │ ├─┬POST
│ │ │ └──[M] description (4261:20)
│ │ └─┬DELETE
│ │   └──[M] description (4361:20)
│ ├─┬/orgs/{org}/actions/permissions/workflow
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (3912:14)
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (3943:14)
│ ├─┬/orgs/{org}/actions/secrets/{secret_name}
│ │ ├─┬GET
│ │ │ └──[M] description (4496:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (4526:20)
│ │ └─┬DELETE
│ │   └──[M] description (4680:20)
│ ├─┬/users/{username}/packages
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (42832:14)
│ ├─┬/repos/{owner}/{repo}/pages/builds/{build_id}
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (30082:14)
│ ├─┬/orgs/{org}/packages/{package_type}/{package_name}/versions/{package_version_id}
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (9244:14)
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment_protection_rules
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (24576:14)
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (24639:14)
│ ├─┬/repos/{owner}/{repo}/actions/runners/remove-token
│ │ └─┬POST
│ │   └──[M] description (14846:20)
│ ├─┬/orgs/{org}/actions/runners/downloads
│ │ └─┬GET
│ │   └──[M] description (4011:20)
│ ├─┬/orgs/{org}/packages/{package_type}/{package_name}/versions
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (9158:14)
│ ├─┬/repos/{owner}/{repo}/readme/{dir}
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (32238:14)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/variables/{name}
│ │ ├─┬GET
│ │ │ └──[M] description (35552:20)
│ │ ├─┬DELETE
│ │ │ └──[M] description (35624:20)
│ │ └─┬PATCH
│ │   └──[M] description (35582:20)
│ ├─┬/meta
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (2777:14)
│ ├─┬/repos/{owner}/{repo}/actions/secrets/{secret_name}
│ │ ├─┬GET
│ │ │ └──[M] description (15985:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (16016:20)
│ │ └─┬DELETE
│ │   └──[M] description (16144:20)
│ ├─┬/users/{username}/packages/{package_type}/{package_name}/versions
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (42997:14)
│ ├─┬/orgs/{org}/rulesets
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (10275:14)
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (10309:14)
│ ├─┬/orgs/{org}/actions/runners/{runner_id}/labels/{name}
│ │ └─┬DELETE
│ │   └──[M] description (4388:20)
│ ├─┬/repos/{owner}/{repo}/tags/protection/{tag_protection_id}
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (34573:14)
│ ├─┬/repos/{owner}/{repo}/actions/permissions/access
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (14475:14)
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (14509:14)
│ ├─┬/repos/{owner}/{repo}/actions/secrets
│ │ └─┬GET
│ │   └──[M] description (15907:20)
│ ├─┬/repos/{owner}/{repo}/releases/generate-notes
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (32550:14)
│ ├─┬/orgs/{org}/actions/secrets/{secret_name}/repositories
│ │ ├─┬GET
│ │ │ └──[M] description (4704:20)
│ │ └─┬PUT
│ │   └──[M] description (4746:20)
│ ├─┬/user/packages
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (40901:14)
│ ├─┬/repos/{owner}/{repo}/actions/runners/{runner_id}
│ │ ├─┬GET
│ │ │ └──[M] description (14879:20)
│ │ └─┬DELETE
│ │   └──[M] description (14911:20)
│ ├─┬/repos/{owner}/{repo}/actions/organization-secrets
│ │ └─┬GET
│ │   └──[M] description (14299:20)
│ ├─┬/orgs/{org}/actions/variables/{name}/repositories/{repository_id}
│ │ ├─┬PUT
│ │ │ └──[M] description (5188:20)
│ │ └─┬DELETE
│ │   └──[M] description (5221:20)
│ ├─┬/users/{username}/docker/conflicts
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (42372:14)
│ ├─┬/user/ssh_signing_keys
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (41888:14)
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (41932:14)
│ ├─┬/repos/{owner}/{repo}/pages
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (29736:14)
│ │ ├─┬PUT
│ │ │ └─┬External Docs
│ │ │   └──[M] url (29851:14)
│ │ ├─┬POST
│ │ │ └─┬External Docs
│ │ │   └──[M] url (29768:14)
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (29953:14)
│ ├─┬/repos/{owner}/{repo}/rulesets/{ruleset_id}
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (33257:14)
│ │ ├─┬PUT
│ │ │ └─┬External Docs
│ │ │   └──[M] url (33302:14)
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (33392:14)
│ ├─┬/repos/{owner}/{repo}/actions/jobs/{job_id}/rerun
│ │ └─┬POST
│ │   ├──[M] description (14151:20)
│ │   └─┬External Docs
│ │     └──[M] url (14159:14)
│ ├─┬/orgs/{org}/{security_product}/{enablement}
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (12373:14)
│ ├─┬/orgs/{org}/personal-access-token-requests
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (9369:14)
│ ├─┬/orgs/{org}/actions/runners/{runner_id}
│ │ ├─┬GET
│ │ │ └──[M] description (4182:20)
│ │ └─┬DELETE
│ │   └──[M] description (4212:20)
│ ├─┬/repos/{owner}/{repo}/actions/runs/{run_id}/deployment_protection_rule
│ │ └─┬POST
│ │   └──[M] description (15511:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/{runner_id}/labels/{name}
│ │ └─┬DELETE
│ │   └──[M] description (15097:20)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/secrets/public-key
│ │ └─┬GET
│ │   └──[M] description (35237:20)
│ ├─┬/orgs/{org}/actions/runners/generate-jitconfig
│ │ └─┬POST
│ │   └──[M] description (4043:20)
│ ├─┬/repos/{owner}/{repo}/actions/runs/{run_id}/rerun-failed-jobs
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (15836:14)
│ ├─┬/repos/{owner}/{repo}/actions/artifacts/{artifact_id}/{archive_format}
│ │ └─┬GET
│ │   └──[M] description (13919:20)
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment_protection_rules/{protection_rule_id}
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (24734:14)
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (24766:14)
│ ├─┬/repos/{owner}/{repo}/actions/variables/{name}
│ │ ├─┬GET
│ │ │ └──[M] description (16264:20)
│ │ ├─┬DELETE
│ │ │ └──[M] description (16336:20)
│ │ └─┬PATCH
│ │   └──[M] description (16294:20)
│ ├─┬/users/{username}/packages/{package_type}/{package_name}/versions/{package_version_id}/restore
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (43109:14)
│ ├─┬/repos/{owner}/{repo}/tags/protection
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (34487:14)
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (34522:14)
│ ├─┬/projects/columns/cards/{card_id}
│ │ └─┬PATCH
│ │   └─┬External Docs
│ │     └──[M] url (12451:14)
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment_protection_rules/apps
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (24688:14)
│ ├─┬/repos/{owner}/{repo}/pages/builds
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (29983:14)
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (30020:14)
│ ├─┬/repos/{owner}/{repo}/tarball/{ref}
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (34602:14)
│ ├─┬/user/docker/conflicts
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (39146:14)
│ ├─┬/user/social_accounts
│ │ ├─┬POST
│ │ │ └─┬External Docs
│ │ │   └──[M] url (41762:14)
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (41828:14)
│ ├─┬/repos/{owner}/{repo}/codespaces/new
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (21077:14)
│ ├─┬/repos/{owner}/{repo}/zipball/{ref}
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (35033:14)
│ ├─┬/repos/{owner}/{repo}/dependency-graph/compare/{basehead}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬403
│ │       └──[M] description (227532:20)
│ ├─┬/projects/columns/{column_id}
│ │ └─┬PATCH
│ │   └─┬External Docs
│ │     └──[M] url (12696:14)
│ ├─┬/orgs/{org}/packages/{package_type}/{package_name}/versions/{package_version_id}/restore
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (9282:14)
│ ├─┬/repos/{owner}/{repo}/git/commits/{commit_sha}
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (25244:14)
│ ├─┬/repos/{owner}/{repo}/actions/runners/registration-token
│ │ └─┬POST
│ │   └──[M] description (14813:20)
│ ├─┬/repos/{owner}/{repo}/actions/variables
│ │ ├─┬GET
│ │ │ └──[M] description (16168:20)
│ │ └─┬POST
│ │   └──[M] description (16212:20)
│ ├─┬/orgs/{org}/actions/variables/{name}
│ │ ├─┬GET
│ │ │ └──[M] description (4978:20)
│ │ ├─┬DELETE
│ │ │ └──[M] description (5069:20)
│ │ └─┬PATCH
│ │   └──[M] description (5008:20)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/variables
│ │ ├─┬GET
│ │ │ └──[M] description (35456:20)
│ │ └─┬POST
│ │   └──[M] description (35500:20)
│ ├─┬/orgs/{org}/actions/runners/registration-token
│ │ └─┬POST
│ │   └──[M] description (4111:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners
│ │ └─┬GET
│ │   └──[M] description (14667:20)
│ ├─┬/repos/{owner}/{repo}/branches/{branch}/protection/restrictions/teams
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (18428:14)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/secrets/{secret_name}
│ │ ├─┬GET
│ │ │ └──[M] description (35270:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (35301:20)
│ │ └─┬DELETE
│ │   └──[M] description (35432:20)
│ ├─┬/orgs/{org}/teams/{team_slug}/memberships/{username}
│ │ └─┬GET
│ │   └──[M] description (11869:20)
│ ├─┬/repos/{owner}/{repo}/codespaces/devcontainers
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (20947:14)
│ ├─┬/orgs/{org}/actions/secrets/{secret_name}/repositories/{repository_id}
│ │ ├─┬PUT
│ │ │ └──[M] description (4797:20)
│ │ └─┬DELETE
│ │   └──[M] description (4829:20)
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment-branch-policies
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (24422:14)
│ ├─┬/user/ssh_signing_keys/{ssh_signing_key_id}
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (41996:14)
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (42033:14)
│ ├─┬/orgs/{org}/actions/permissions/selected-actions
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (3849:14)
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (3878:14)
│ ├─┬/orgs/{org}/rulesets/{ruleset_id}
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (10396:14)
│ │ ├─┬PUT
│ │ │ └─┬External Docs
│ │ │   └──[M] url (10432:14)
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (10521:14)
│ ├─┬/orgs/{org}/members/{username}/codespaces
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (8216:14)
│ └─┬/repos/{owner}/{repo}/actions/runners/downloads
│   └─┬GET
│     └──[M] description (14711:20)
└─┬Components
  ├──[-] responses (228065:7)❌
  ├──[-] examples (212354:7)❌
  └──[-] schemas (70890:7)❌

Date: 07/26/23 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 152           | 1
components       | 3             | 3
❌  4 Breaking changes out of 155
INFO: Modifications: 151
INFO: Removals: 4
INFO: Breaking Removals: 4

ERROR: breaking changes discovered