[GitHub] Update to 1.1.4-71df6aeea9b73116fc9b87e18d680d1b from 1.1.4-2a026b6521435116fded9a6411ccf743 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit d56906
                                                                                SPEC: extracted 2 commits from history
                                                                                DONE: completed

├─┬Paths
│ ├─┬/orgs/{org}/invitations
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬role
│ │           ├──[-] enum (8169:21)❌
│ │           └──[M] description (8155:32)
│ ├─┬/repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}/locations
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (229338:7)
│ ├─┬/repos/{template_owner}/{template_repo}/generate
│ │ └─┬POST
│ │   └──[M] description (36747:20)
│ ├─┬/user/repos
│ │ └─┬POST
│ │   └──[M] description (42973:20)
│ ├─┬/users/{username}/repos
│ │ └─┬GET
│ │   └──[M] description (44814:20)
│ └─┬/orgs/{org}/repos
│   └─┬POST
│     └──[M] description (11308:20)
└─┬Components
  ├──[-] schemas (83828:7)❌
  ├──[-] schemas (83814:7)❌
  ├──[-] schemas (83856:7)❌
  ├──[-] schemas (83842:7)❌
  ├──[-] schemas (83871:7)❌
  ├──[-] schemas (83801:7)❌
  ├──[-] schemas (83886:7)❌
  ├──[-] schemas (83788:7)❌
  ├─┬api-overview
  │ └─┬domains
  │   └──[-] properties (66750:13)❌
  ├─┬repository-webhooks
  │ └─┬size
  │   └──[M] description (86770:24)
  ├─┬minimal-repository
  │ └─┬size
  │   └──[M] description (67016:24)
  ├─┬full-repository
  │ └─┬size
  │   └──[M] description (70303:24)
  ├─┬secret-scanning-location
  │ ├─┬type
  │ │ ├──[-] enum (83913:13)❌
  │ │ ├──[-] enum (83914:13)❌
  │ │ ├──[-] enum (83915:13)❌
  │ │ ├──[-] enum (83916:13)❌
  │ │ ├──[-] enum (83910:13)❌
  │ │ ├──[-] enum (83911:13)❌
  │ │ ├──[-] enum (83912:13)❌
  │ │ ├──[-] enum (83917:13)❌
  │ │ └──[M] description (83788:24)
  │ └─┬details
  │   ├──[-] oneOf (83871:7)❌
  │   ├──[-] oneOf (83699:7)❌
  │   ├──[-] oneOf (83775:7)❌
  │   ├──[-] oneOf (83801:7)❌
  │   ├──[-] oneOf (83749:7)❌
  │   ├──[-] oneOf (83842:7)❌
  │   ├──[-] oneOf (83856:7)❌
  │   ├──[-] oneOf (83814:7)❌
  │   ├─┬ONEOF
  │   │ └──[M] $ref (83753:20)❌
  │   ├─┬ONEOF
  │   │ └──[M] $ref (83690:20)❌
  │   ├─┬ONEOF
  │   │ └──[M] $ref (83766:20)❌
  │   └─┬ONEOF
  │     └──[M] $ref (83740:20)❌
  └─┬repository
    └─┬size
      └──[M] description (63072:24)

Date: 12/02/23 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 7             | 1
components       | 34            | 29

❌  30 Breaking changes out of 41
INFO: Modifications: 15
INFO: Removals: 26
INFO: Breaking Removals: 26
INFO: Breaking Modifications: 4

ERROR: breaking changes discovered