[GitHub] Update to 1.1.4-4cf5c64422925cf50a90b6e402d5aa38 from 1.1.4-97ae665c50dc0af2640cf572009dd76b Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit b185fb
                                                                                SPEC: extracted 2 commits from history

```
├──[➖] webhooks (57313:5)❌
├──[➖] webhooks (57447:5)❌
├──[➖] webhooks (57380:5)❌
├─┬Paths
│ ├──[➖] path (45866:3)❌
│ └─┬/repos/{owner}/{repo}/dependency-graph/sbom
│   └─┬GET
│     └─┬Responses
│       └─┬200
│         └─┬application/json
│           └─┬default
│             └──[🔀] value (210707:9)
└─┬Components
  ├──[➖] schemas (130858:7)❌
  ├──[➖] schemas (130879:7)❌
  ├──[➖] schemas (130900:7)❌
  ├──[➖] schemas (95640:7)❌
  ├─┬deployment
  │ └─┬id
  │   └──[➖] format (77089:19)❌
  ├─┬organization-role
  │ └─┬id
  │   └──[➖] format (72018:19)❌
  ├─┬pending-deployment
  │ └─┬environment
  │   └─┬id
  │     └──[➖] format (77017:23)❌
  ├─┬deployment-status
  │ └─┬id
  │   └──[➖] format (81731:19)❌
  ├─┬repository-ruleset-conditions-repository-property-spec
  │ └──[➖] properties (73388:9)❌
  ├─┬authorization
  │ └─┬id
  │   └──[➖] format (65864:19)❌
  ├─┬review-comment
  │ ├─┬id
  │ │ └──[➖] format (86407:19)❌
  │ └─┬pull_request_review_id
  │   └──[➖] format (86402:19)❌
  ├─┬dependency-graph-spdx-sbom
  │ └─┬sbom
  │   └─┬packages
  │     └─┬Schema
  │       └──[➖] properties (81485:19)❌
  ├─┬pull-request-minimal
  │ ├─┬id
  │ │ └──[➖] format (76559:19)❌
  │ ├─┬head
  │ │ └─┬repo
  │ │   └─┬id
  │ │     └──[➖] format (76576:27)❌
  │ └─┬base
  │   └─┬repo
  │     └─┬id
  │       └──[➖] format (76601:27)❌
  ├─┬pull-request-simple
  │ └─┬id
  │   └──[➖] format (80005:19)❌
  ├─┬pull-request-review-comment
  │ ├─┬id
  │ │ └──[➖] format (84079:19)❌
  │ └─┬pull_request_review_id
  │   └──[➖] format (84073:19)❌
  └─┬pull-request
    └─┬id
      └──[➖] format (85051:19)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 2             | 1                |
| components       | 20            | 20               |

Date: 06/27/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _21_ out of _22_
- **Modifications**: _1_
- **Removals**: _24_
- **Breaking Removals**: _24_

ERROR: breaking changes discovered