[GitHub] Update to 1.1.4-7d381dcec5cc31f738fdd8a803bade45 from 1.1.4-28a997033a88fffc4459106785ce7992 Detected Schema changes:
```
├─┬Paths
│ ├─┬/enterprises/{enterprise}/code-security/configurations
│ │ └─┬POST
│ │   ├─┬Responses
│ │   │ └─┬201
│ │   │   └─┬application/json
│ │   │     └─┬default
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[➖] value (205204:9)
│ │   │       └──[➖] value (205204:9)
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         ├──[➖] properties (1576:17)❌
│ │         └──[➖] properties (1626:17)❌
│ ├─┬/orgs/{org}/code-security/configurations/{configuration_id}
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         ├──[🔀] value (205202:9)
│ │ │         ├──[🔀] value (205202:9)
│ │ │         ├──[🔀] value (205202:9)
│ │ │         ├──[🔀] value (205202:9)
│ │ │         ├──[🔀] value (205202:9)
│ │ │         ├──[🔀] value (205202:9)
│ │ │         ├──[🔀] value (205202:9)
│ │ │         ├──[🔀] value (205202:9)
│ │ │         ├──[🔀] value (205202:9)
│ │ │         ├──[🔀] value (205202:9)
│ │ │         ├──[🔀] value (205202:9)
│ │ │         ├──[🔀] value (205202:9)
│ │ │         ├──[🔀] value (205202:9)
│ │ │         ├──[🔀] value (205202:9)
│ │ │         ├──[🔀] value (205202:9)
│ │ │         ├──[🔀] value (205202:9)
│ │ │         ├──[🔀] value (205202:9)
│ │ │         ├──[🔀] value (205202:9)
│ │ │         ├──[🔀] value (205202:9)
│ │ │         ├──[🔀] value (205202:9)
│ │ │         ├──[🔀] value (205202:9)
│ │ │         ├──[➖] value (205295:9)
│ │ │         └──[➖] value (205295:9)
│ │ └─┬PATCH
│ │   ├─┬Responses
│ │   │ └─┬200
│ │   │   └─┬application/json
│ │   │     └─┬default
│ │   │       ├──[🔀] value (208534:9)
│ │   │       ├──[🔀] value (208534:9)
│ │   │       ├──[🔀] value (208534:9)
│ │   │       ├──[🔀] value (208534:9)
│ │   │       ├──[🔀] value (208534:9)
│ │   │       ├──[🔀] value (208534:9)
│ │   │       ├──[🔀] value (208534:9)
│ │   │       ├──[🔀] value (208534:9)
│ │   │       ├──[🔀] value (208534:9)
│ │   │       ├──[🔀] value (208534:9)
│ │   │       ├──[🔀] value (208534:9)
│ │   │       ├──[🔀] value (208534:9)
│ │   │       ├──[🔀] value (208534:9)
│ │   │       ├──[🔀] value (208534:9)
│ │   │       ├──[🔀] value (208534:9)
│ │   │       ├──[🔀] value (208534:9)
│ │   │       ├──[🔀] value (208534:9)
│ │   │       ├──[🔀] value (208534:9)
│ │   │       ├──[🔀] value (208534:9)
│ │   │       ├──[🔀] value (208534:9)
│ │   │       ├──[🔀] value (208534:9)
│ │   │       ├──[➖] value (208631:9)
│ │   │       └──[➖] value (208631:9)
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └──[➖] properties (8324:17)❌
│ ├─┬/repos/{owner}/{repo}/code-security-configuration
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (216377:9)
│ ├─┬/enterprises/{enterprise}/code-security/configurations/{configuration_id}
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         ├──[🔀] value (205113:9)
│ │ │         ├──[🔀] value (205113:9)
│ │ │         ├──[🔀] value (205113:9)
│ │ │         ├──[🔀] value (205113:9)
│ │ │         ├──[🔀] value (205113:9)
│ │ │         ├──[🔀] value (205113:9)
│ │ │         ├──[🔀] value (205113:9)
│ │ │         ├──[🔀] value (205113:9)
│ │ │         ├──[🔀] value (205113:9)
│ │ │         ├──[🔀] value (205113:9)
│ │ │         ├──[🔀] value (205113:9)
│ │ │         ├──[🔀] value (205113:9)
│ │ │         ├──[🔀] value (205113:9)
│ │ │         ├──[🔀] value (205113:9)
│ │ │         ├──[🔀] value (205113:9)
│ │ │         ├──[🔀] value (205113:9)
│ │ │         ├──[🔀] value (205113:9)
│ │ │         ├──[🔀] value (205113:9)
│ │ │         ├──[🔀] value (205113:9)
│ │ │         ├──[🔀] value (205113:9)
│ │ │         ├──[🔀] value (205113:9)
│ │ │         ├──[➖] value (205204:9)
│ │ │         └──[➖] value (205204:9)
│ │ └─┬PATCH
│ │   ├─┬Responses
│ │   │ └─┬200
│ │   │   └─┬application/json
│ │   │     └─┬default
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[🔀] value (205113:9)
│ │   │       ├──[➖] value (205204:9)
│ │   │       └──[➖] value (205204:9)
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         ├──[➖] properties (1840:17)❌
│ │         └──[➖] properties (1886:17)❌
│ └─┬/orgs/{org}/code-security/configurations
│   ├─┬GET
│   │ └─┬Responses
│   │   └─┬200
│   │     └─┬application/json
│   │       └─┬default
│   │         └──[🔀] value (208477:7)
│   └─┬POST
│     ├─┬Responses
│     │ └─┬201
│     │   └─┬application/json
│     │     └─┬default
│     │       ├──[🔀] value (205202:9)
│     │       ├──[🔀] value (205202:9)
│     │       ├──[🔀] value (205202:9)
│     │       ├──[🔀] value (205202:9)
│     │       ├──[🔀] value (205202:9)
│     │       ├──[🔀] value (205202:9)
│     │       ├──[🔀] value (205202:9)
│     │       ├──[🔀] value (205202:9)
│     │       ├──[🔀] value (205202:9)
│     │       ├──[🔀] value (205202:9)
│     │       ├──[🔀] value (205202:9)
│     │       ├──[🔀] value (205202:9)
│     │       ├──[🔀] value (205202:9)
│     │       ├──[🔀] value (205202:9)
│     │       ├──[🔀] value (205202:9)
│     │       ├──[🔀] value (205202:9)
│     │       ├──[🔀] value (205202:9)
│     │       ├──[🔀] value (205202:9)
│     │       ├──[🔀] value (205202:9)
│     │       ├──[🔀] value (205202:9)
│     │       ├──[🔀] value (205202:9)
│     │       ├──[➖] value (205295:9)
│     │       └──[➖] value (205295:9)
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └──[➖] properties (7974:17)❌
└─┬Components
  ├─┬dependabot-alert
  │ └─┬dependency
  │   └──[➖] properties (87266:13)❌
  ├─┬code-security-configuration
  │ └──[➖] properties (71107:9)❌
  └─┬dependabot-alert-with-repository
    └─┬dependency
      └──[➖] properties (71888:13)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 146           | 6                |
| components       | 3             | 3                |

Date: 03/06/25 | Commit: Original: etc/specs/GitHub/current.spec.yaml, Modified: etc/specs/GitHub/previous.spec.yaml,

- ❌ **BREAKING Changes**: _9_ out of _149_
- **Modifications**: _128_
- **Removals**: _21_
- **Breaking Removals**: _9_

ERROR: breaking changes discovered