[GitHub] Update to 1.1.4-70c15d3e8826de45231fa16fc40897e0 from 1.1.4-864f215bcb7fda8ed79c1295fb5a81d2 Detected Schema changes:
```
├─┬Paths
│ ├─┬/orgs/{org}/actions/hosted-runners/{hosted_runner_id}
│ │ └─┬PATCH
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       ├─┬Schema
│ │       │ ├──[➕] properties (5235:17)
│ │       │ ├─┬runner_group_id
│ │       │ │ ├──[🔀] type (5221:25)❌
│ │       │ │ └──[🔀] description (5218:32)
│ │       │ ├─┬name
│ │       │ │ ├──[🔀] type (5229:25)❌
│ │       │ │ └──[🔀] description (5226:32)
│ │       │ └─┬maximum_runners
│ │       │   ├──[🔀] type (5239:19)❌
│ │       │   └──[🔀] description (5236:32)
│ │       └─┬default
│ │         ├──[🔀] value (5244:19)
│ │         ├──[🔀] value (5244:19)
│ │         ├──[🔀] value (5244:19)
│ │         └──[➕] value (5244:19)
│ └─┬/orgs/{org}/actions/hosted-runners
│   └─┬POST
│     └─┬Requestbody
│       └─┬application/json
│         ├─┬Schema
│         │ └─┬image
│         │   └──[➕] properties (4924:21)
│         └─┬default
│           └──[🔀] value (4955:19)
└─┬Components
  └─┬actions-hosted-runner-pool-image
    └──[➕] properties (74869:9)

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 13            | 3                |
| components       | 1             | 0                |

Date: 03/08/25 | Commit: Original: etc/specs/GitHub/current.spec.yaml, Modified: etc/specs/GitHub/previous.spec.yaml,

- ❌ **BREAKING Changes**: _3_ out of _14_
- **Modifications**: _10_
- **Additions**: _4_
- **Breaking Modifications**: _3_

ERROR: breaking changes discovered