[GitHub] Update to 1.1.4-c1edbd9927fe103e94027b18d46aa0e4 from 1.1.4-a937c40b238be216f274ad4de79f6216 Detected Schema changes:
```
├─┬Paths
│ └─┬/advisories
│   └─┬GET
│     └─┬Parameters
│       └─┬Schema
│         ├──[➖] enum (270:13)❌
│         └──[➖] enum (269:13)❌
└─┬Components
  └─┬repository-ruleset-bypass-actor
    └─┬actor_type
      └──[➕] enum (73901:13)

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 2             | 2                |
| components       | 1             | 0                |

Date: 08/31/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _2_ out of _3_
- **Removals**: _2_
- **Additions**: _1_
- **Breaking Removals**: _2_

ERROR: breaking changes discovered