[GitHub] Update to 1.1.4-bd1a2cde4ef1f12a463c3206d4665fb8 from 1.1.4-ed9f9c8a528083c4f510bc9ec29e7cbc Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 1f1e00
```
                                                                                SPEC: extracted 2 commits from history
└─┬Components
  └─┬commit
    ├─┬committer
    │ ├──[➖] type (78129:11)❌
    │ ├──[➕] anyOf (78123:13)
    │ ├──[➕] anyOf (63803:7)
    │ ├──[➖] oneOf (70391:7)❌
    │ └──[➖] oneOf (63803:7)❌
    └─┬author
      ├──[➖] type (78122:11)❌
      ├──[➕] anyOf (78119:13)
      ├──[➕] anyOf (63803:7)
      ├──[➖] oneOf (70391:7)❌
      └──[➖] oneOf (63803:7)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| components       | 10            | 6                |

Date: 07/10/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _6_ out of _10_
- **Removals**: _6_
- **Additions**: _4_
- **Breaking Removals**: _6_

ERROR: breaking changes discovered