[GitHub] Update to 1.1.4-31d970a125b23e50df0d710a170852d6 from 1.1.4-627e7866ca107dff7a8236c103eb53a4 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit ec47fd
```
                                                                                SPEC: extracted 2 commits from history
└─┬Components
  ├──[➖] schemas (88396:7)❌
  ├──[➖] schemas (62220:7)❌
  └─┬global-advisory
    └─┬vulnerabilities
      └─┬Schema
        └──[🔀] $ref (62483:13)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| components       | 3             | 3                |

Date: 04/20/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _3_
- **Modifications**: _1_
- **Removals**: _2_
- **Breaking Removals**: _2_
- **Breaking Modifications**: _1_

ERROR: breaking changes discovered