[GitHub] Update to 1.1.4-a5a20c93e8ace47c79943304e911cf70 from 1.1.4-ee23af97204cde51d4c62161bf274df2 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 25d714
                                                                                SPEC: extracted 2 commits from history

```
├─┬Paths
│ └─┬/orgs/{org}/{security_product}/{enablement}
│   └─┬POST
│     └──[🔀] description (14735:20)
└─┬Components
  └─┬code-security-configuration-repositories
    └─┬status
      ├──[➖] enum (71146:13)❌
      └──[➖] enum (71142:13)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 1             | 0                |
| components       | 2             | 2                |

Date: 07/23/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _2_ out of _3_
- **Modifications**: _1_
- **Removals**: _2_
- **Breaking Removals**: _2_

ERROR: breaking changes discovered