[GitHub] Update to 1.1.4-43512e093bc0645d14a6d505678dad79 from 1.1.4-f5f9e60e15bc4ad8d390c412dd58fac6 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 0b33ea
                                                                                SPEC: extracted 2 commits from history
                                                                                DONE: completed

├─┬Paths
│ ├─┬/orgs/{org}/properties/schema/{custom_property_name}
│ │ └─┬PUT
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬allowed_values
│ │           ├──[-] maxItems (11065:29)❌
│ │           ├──[M] description (11064:32)
│ │           └─┬Schema
│ │             └──[-] maxLength (11064:32)❌
│ └─┬/apps/{app_slug}
│   └─┬GET
│     └──[M] description (1124:20)
└─┬Components
  └─┬org-custom-property
    └─┬allowed_values
      ├──[-] maxItems (70701:21)❌
      ├──[M] description (70696:24)
      └─┬Schema
        └──[-] maxLength (70700:24)❌

Date: 01/29/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 4             | 2
components       | 3             | 2

❌  4 Breaking changes out of 7
INFO: Modifications: 3
INFO: Removals: 4
INFO: Breaking Removals: 4

ERROR: breaking changes discovered