[GitHub] Update to 1.1.4-08747ed797271fdcb119e705571bb8c5 from 1.1.4-e8f314439d74f777d80051506251feea Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 2a6850
                                                                                SPEC: extracted 2 commits from history
                                                                                DONE: completed

├─┬Paths
│ ├─┬/user/codespaces/{codespace_name}
│ │ ├─┬GET
│ │ │ └──[M] description (40365:20)
│ │ ├─┬DELETE
│ │ │ └──[M] description (40469:20)
│ │ └─┬PATCH
│ │   └──[M] description (40406:20)
│ ├─┬/repos/{owner}/{repo}/stats/code_frequency
│ │ └─┬GET
│ │   ├──[M] description (35795:20)
│ │   └─┬Responses
│ │     └──[-] codes (35843:11)❌
│ ├─┬/user/codespaces
│ │ ├─┬GET
│ │ │ └──[M] description (39765:20)
│ │ └─┬POST
│ │   └──[M] description (39818:20)
│ ├─┬/user/codespaces/{codespace_name}/publish
│ │ └─┬POST
│ │   └──[M] description (40635:20)
│ ├─┬/repos/{owner}/{repo}/codespaces
│ │ ├─┬GET
│ │ │ └──[M] description (22377:20)
│ │ └─┬POST
│ │   └──[M] description (22429:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/codespaces
│ │ └─┬POST
│ │   └──[M] description (32576:20)
│ ├─┬/repos/{owner}/{repo}/stats/contributors
│ │ └─┬GET
│ │   └──[M] description (35866:20)
│ ├─┬/repos/{owner}/{repo}/codespaces/permissions_check
│ │ └─┬GET
│ │   └──[M] description (22752:20)
│ └─┬/repos/{owner}/{repo}/codespaces/new
│   └─┬GET
│     └──[M] description (22680:20)
└─┬Components
  └─┬repository-ruleset
    └─┬conditions
      └──[-] type (71416:11)❌

Date: 01/10/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml
Document Element | Total Changes | Breaking Changes
components       | 1             | 1
paths            | 14            | 1

❌  2 Breaking changes out of 15
INFO: Modifications: 13
INFO: Removals: 2
INFO: Breaking Removals: 2

ERROR: breaking changes discovered