[GitHub] Update to 1.1.4-529209138ca3f128f373739100dbd53c from 1.1.4-4298b69a1afaf61496dd8894c7a47c3a Detected Schema changes:
```
├─┬Paths
│ └─┬/repos/{owner}/{repo}/automated-security-fixes
│   ├─┬GET
│   │ ├──[🔀] summary (21687:16)
│   │ ├──[🔀] description (21688:20)
│   │ └─┬External Docs
│   │   └──[🔀] url (21697:14)
│   ├─┬PUT
│   │ ├──[🔀] summary (21721:16)
│   │ ├──[🔀] description (21722:20)
│   │ └─┬External Docs
│   │   └──[🔀] url (21730:14)
│   └─┬DELETE
│     ├──[🔀] summary (21743:16)
│     ├──[🔀] description (21744:20)
│     └─┬External Docs
│       └──[🔀] url (21752:14)
└─┬Components
  ├─┬check-automated-security-fixes
  │ ├──[🔀] title (81678:14)
  │ ├──[🔀] description (81679:20)
  │ ├─┬enabled
  │ │ └──[🔀] description (81684:24)
  │ └─┬paused
  │   └──[🔀] description (81689:24)
  └─┬enterprise-team
    └──[➖] properties (74872:9)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 9             | 0                |
| components       | 5             | 1                |

Date: 01/14/25 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _1_ out of _14_
- **Modifications**: _13_
- **Removals**: _1_
- **Breaking Removals**: _1_

ERROR: breaking changes discovered