[GitHub] Update to 1.1.4-758801dbed7c532f009e5f428e0454a9 from 1.1.4-569ed36cc004e0f3ecba0e072fcfa984 Detected Schema changes:
```
├─┬Paths
│ ├──[➕] path (1766:3)
│ ├──[➕] path (1578:3)
│ ├──[➕] path (1436:3)
│ ├──[➕] path (1507:3)
│ ├──[➕] path (1844:3)
│ ├─┬/orgs/{org}/secret-scanning/alerts
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (202748:7)
│ ├─┬/repos/{owner}/{repo}/secret-scanning/alerts
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (220483:7)
│ ├─┬/users/{username}/attestations/{subject_digest}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬Schema
│ │           └─┬attestations
│ │             └─┬Schema
│ │               └──[➖] properties (47530:25)❌
│ ├─┬/repos/{owner}/{repo}/attestations/{subject_digest}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬Schema
│ │           └─┬attestations
│ │             └─┬Schema
│ │               └──[➖] properties (20467:25)❌
│ ├─┬/repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         ├──[🔀] value (220583:9)
│ │ │         ├──[🔀] value (220583:9)
│ │ │         ├──[🔀] value (220583:9)
│ │ │         ├──[🔀] value (220583:9)
│ │ │         ├──[🔀] value (220583:9)
│ │ │         ├──[🔀] value (220583:9)
│ │ │         ├──[🔀] value (220583:9)
│ │ │         ├──[🔀] value (220583:9)
│ │ │         ├──[🔀] value (220583:9)
│ │ │         ├──[🔀] value (220583:9)
│ │ │         ├──[🔀] value (220583:9)
│ │ │         ├──[🔀] value (220583:9)
│ │ │         ├──[🔀] value (220583:9)
│ │ │         └──[➖] value (220191:9)
│ │ └─┬PATCH
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[🔀] value (220607:9)
│ │           ├──[🔀] value (220607:9)
│ │           ├──[🔀] value (220607:9)
│ │           ├──[🔀] value (220607:9)
│ │           ├──[🔀] value (220607:9)
│ │           ├──[🔀] value (220607:9)
│ │           ├──[🔀] value (220607:9)
│ │           ├──[🔀] value (220607:9)
│ │           ├──[🔀] value (220607:9)
│ │           ├──[🔀] value (220607:9)
│ │           ├──[🔀] value (220607:9)
│ │           ├──[🔀] value (220607:9)
│ │           ├──[🔀] value (220607:9)
│ │           └──[➖] value (220216:9)
│ ├─┬/enterprises/{enterprise}/secret-scanning/alerts
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (202748:7)
│ ├─┬/orgs/{org}/rulesets
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬target
│ │           └──[➖] enum (13371:21)❌
│ ├─┬/orgs/{org}/attestations/{subject_digest}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬Schema
│ │           └─┬attestations
│ │             └─┬Schema
│ │               └──[➖] properties (6389:25)❌
│ ├─┬/orgs/{org}/rulesets/{ruleset_id}
│ │ └─┬PUT
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬target
│ │           └──[➖] enum (13588:21)❌
│ ├─┬/rate_limit
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (209556:9)
│ └─┬/orgs/{org}/properties/schema/{custom_property_name}
│   └─┬PUT
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └──[🔀] $ref (13109:15)❌
└─┬Components
  ├──[➕] parameters (226707:7)
  ├──[➕] examples (202372:7)
  ├──[➖] schemas (75329:7)❌
  ├─┬secret-scanning-alert-webhook
  │ └──[➖] properties (101570:9)❌
  ├─┬rate-limit-overview
  │ └─┬resources
  │   └──[➖] properties (78921:13)❌
  ├─┬organization-secret-scanning-alert
  │ └──[➖] properties (69281:9)❌
  ├─┬repository-rule-pull-request
  │ └─┬parameters
  │   └──[➖] properties (76383:13)❌
  ├─┬repository-ruleset
  │ ├─┬source_type
  │ │ └──[➖] enum (76902:13)❌
  │ └─┬target
  │   └──[➖] enum (76895:13)❌
  ├─┬secret-scanning-alert
  │ └──[➖] properties (88985:9)❌
  └─┬org-ruleset-conditions
    └──[🔀] description (76520:20)

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 43            | 6                |
| components       | 11            | 8                |

Date: 12/12/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _14_ out of _54_
- **Modifications**: _32_
- **Removals**: _15_
- **Additions**: _7_
- **Breaking Removals**: _13_
- **Breaking Modifications**: _1_

ERROR: breaking changes discovered