[GitHub] Update to 1.1.4-2c0c305301b4db15047c06c5d15a3675 from 1.1.4-95c17fdaedbd73d404bbf04c1d953250 Detected Schema changes:
```
├─┬Paths
│ ├─┬/orgs/{org}
│ │ └─┬GET
│ │   └──[🔀] description (4383:20)
│ ├─┬/orgs/{org}/code-security/configurations
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         └──[🔀] value (208429:7)
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └──[➖] properties (7980:17)❌
│ ├─┬/orgs/{org}/code-security/configurations/{configuration_id}
│ │ └─┬PATCH
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └──[➖] properties (8308:17)❌
│ ├─┬/repos/{owner}/{repo}/code-security-configuration
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (216326:9)
│ └─┬/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}/autofix/commits
│   └─┬POST
│     └──[🔀] description (25952:20)
└─┬Components
  ├──[➖] schemas (79091:7)❌
  ├─┬code-security-configuration
  │ └──[➖] properties (71044:9)❌
  └─┬repository-rule-params-required-reviewer-configuration
    ├──[➕] required (79091:9)❌
    ├──[➕] properties (79085:9)
    └──[➖] properties (79124:9)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 6             | 2                |
| components       | 5             | 4                |

Date: 02/26/25 | Commit: Original: etc/specs/GitHub/current.spec.yaml, Modified: etc/specs/GitHub/previous.spec.yaml,

- ❌ **BREAKING Changes**: _6_ out of _11_
- **Modifications**: _4_
- **Removals**: _5_
- **Additions**: _2_
- **Breaking Removals**: _5_
- **Breaking Additions**: _1_

ERROR: breaking changes discovered