[GitHub] Update to 1.1.4-863730273a226f6f485ea390e8766079 from 1.1.4-ce91e6978e30e8f90bf45dbfcabf7a73 Detected Schema changes:
└─┬Paths
  └─┬/orgs/{org}/members/{username}/copilot
    └─┬GET
      └──[M] operationId (8608:20)❌

Date: 10/11/23 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 1             | 1
❌  1 Breaking changes out of 1
INFO: Modifications: 1
INFO: Breaking Modifications: 1

ERROR: breaking changes discovered