[GitHub] Update to 1.1.4-49b27bf070e71e6e97e24f657713d508 from 1.1.4-b5681abce03354e41943d59e8d8bc4a6 Detected Schema changes:
```
└─┬Components
  └─┬repository-ruleset-bypass-actor
    └─┬actor_type
      └──[➖] enum (73349:13)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| components       | 1             | 1                |

Date: 08/13/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _1_ out of _1_
- **Removals**: _1_
- **Breaking Removals**: _1_

ERROR: breaking changes discovered