[GitHub] Update to 1.1.4-b8769452718d6d7793dc313b1b4aae02 from 1.1.4-2b790a7412799c3a2996ba936824dd7d Detected Schema changes:
```
├─┬Paths
│ ├─┬/orgs/{org}/copilot/billing
│ │ └─┬GET
│ │   └──[🔀] description (8338:20)
│ ├─┬/orgs/{org}/personal-access-tokens
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (206614:7)
│ ├─┬/orgs/{org}/members/{username}/copilot
│ │ └─┬GET
│ │   └──[🔀] description (10999:20)
│ ├─┬/orgs/{org}/copilot/billing/seats
│ │ └─┬GET
│ │   └──[🔀] description (8385:20)
│ ├─┬/orgs/{org}/personal-access-token-requests
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (206579:7)
│ ├─┬/enterprises/{enterprise}/copilot/billing/seats
│ │ └─┬GET
│ │   └──[🔀] description (1441:20)
│ ├─┬/orgs/{org}/copilot/billing/selected_teams
│ │ ├─┬POST
│ │ │ ├──[🔀] description (8447:20)
│ │ │ └─┬Responses
│ │ │   └─┬201
│ │ │     └─┬application/json
│ │ │       └─┬Schema
│ │ │         └──[🔀] description (8501:30)
│ │ └─┬DELETE
│ │   ├──[🔀] description (8531:20)
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬Schema
│ │           └──[🔀] description (8583:30)
│ ├─┬/orgs/{org}/copilot/billing/selected_users
│ │ ├─┬POST
│ │ │ ├──[🔀] description (8614:20)
│ │ │ └─┬Responses
│ │ │   └─┬201
│ │ │     └─┬application/json
│ │ │       └─┬Schema
│ │ │         └──[🔀] description (8668:30)
│ │ └─┬DELETE
│ │   ├──[🔀] description (8698:20)
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬Schema
│ │           └──[🔀] description (8750:30)
│ ├─┬/repos/{owner}/{repo}/keys
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         └──[🔀] value (216736:7)
│ │ └─┬POST
│ │   └─┬Responses
│ │     └─┬201
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[🔀] value (216747:9)
│ │           ├──[🔀] value (216747:9)
│ │           ├──[🔀] value (216747:9)
│ │           ├──[🔀] value (216747:9)
│ │           ├──[🔀] value (216747:9)
│ │           ├──[🔀] value (216747:9)
│ │           ├──[🔀] value (216747:9)
│ │           └──[➖] value (216796:9)
│ ├─┬/repos/{owner}/{repo}/keys/{key_id}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[🔀] value (216747:9)
│ │           ├──[🔀] value (216747:9)
│ │           ├──[🔀] value (216747:9)
│ │           ├──[🔀] value (216747:9)
│ │           ├──[🔀] value (216747:9)
│ │           ├──[🔀] value (216747:9)
│ │           ├──[🔀] value (216747:9)
│ │           └──[➖] value (216796:9)
│ └─┬/orgs/{org}
│   ├─┬GET
│   │ └─┬Responses
│   │   └─┬200
│   │     └─┬application/json
│   │       └─┬default-response
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         ├──[🔀] value (203433:9)
│   │         └──[➖] value (203478:9)
│   └─┬PATCH
│     ├─┬Responses
│     │ └─┬200
│     │   └─┬application/json
│     │     └─┬default
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       ├──[🔀] value (203433:9)
│     │       └──[➖] value (203478:9)
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └──[➖] properties (4291:17)❌
└─┬Components
  ├─┬organization-programmatic-access-grant-request
  │ ├──[➖] required (74954:9)❌
  │ └──[➖] properties (74925:9)❌
  ├─┬organization-programmatic-access-grant
  │ ├──[➖] required (75035:9)❌
  │ └──[➖] properties (75007:9)❌
  ├─┬personal-access-token-request
  │ ├──[➖] required (97011:9)❌
  │ └──[➖] properties (96980:9)❌
  ├─┬deploy-key
  │ └──[➖] properties (87202:9)❌
  ├─┬webhooks_deploy_key
  │ └──[➖] properties (93072:9)❌
  └─┬organization-full
    └──[➖] properties (72586:9)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 124           | 1                |
| components       | 9             | 9                |

Date: 11/05/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _10_ out of _133_
- **Modifications**: _119_
- **Removals**: _14_
- **Breaking Removals**: _10_

ERROR: breaking changes discovered