[GitHub] Update to 1.1.4-0479485a780820e347c408d64af6de00 from 1.1.4-c3f89da8f4e736748f0a13e02db3c36d Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 3f3bff
```
                                                                                SPEC: extracted 2 commits from history
                                                                                └─┬Paths
  └──[➖] path (1425:3)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 1             | 1                |

Date: 06/19/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _1_ out of _1_
- **Removals**: _1_
- **Breaking Removals**: _1_

ERROR: breaking changes discovered