[GitHub] Update to 1.1.4 (hash: 569443ee3cd6c4745011d3647afcbfc3) from 1.1.4 (hash: 6d83cf0b9aff678c7dd09cd04153b933) Detected Schema changes:
├──[-] webhooks (56697:5)❌
├──[-] webhooks (56763:5)❌
├──[-] webhooks (45685:5)❌
├──[-] webhooks (45621:5)❌
├──[-] webhooks (50041:5)❌
├──[-] webhooks (50105:5)❌
├──[-] webhooks (45749:5)❌
├──[-] webhooks (56631:5)❌
├─┬Paths
│ ├──[-] path (34012:3)❌
│ ├─┬/orgs/{org}/codespaces/secrets/{secret_name}
│ │ └─┬PUT
│ │   └──[M] description (6058:20)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/secrets/{secret_name}
│ │ └─┬PUT
│ │   └──[M] description (35764:20)
│ ├─┬/meta
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[M] value (207030:9)
│ │           ├──[M] value (207030:9)
│ │           ├──[M] value (207030:9)
│ │           ├──[M] value (207030:9)
│ │           ├──[M] value (207030:9)
│ │           ├──[M] value (207030:9)
│ │           ├──[M] value (207030:9)
│ │           ├──[M] value (207030:9)
│ │           └──[-] value (214094:9)
│ ├─┬/orgs/{org}
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default-response
│ │ │         ├──[M] value (207329:9)
│ │ │         └──[M] value (207329:9)
│ │ └─┬PATCH
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[M] value (207329:9)
│ │           └──[M] value (207329:9)
│ ├─┬/repos/{owner}/{repo}/codespaces/secrets/{secret_name}
│ │ └─┬PUT
│ │   └──[M] description (21703:20)
│ ├─┬/orgs/{org}/dependabot/secrets/{secret_name}
│ │ └─┬PUT
│ │   └──[M] description (6995:20)
│ ├─┬/orgs/{org}/codespaces
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (208062:9)
│ ├─┬/user/codespaces/{codespace_name}/publish
│ │ └─┬POST
│ │   └─┬Responses
│ │     └─┬201
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (224580:9)
│ ├─┬/orgs/{org}/members/{username}/codespaces/{codespace_name}/stop
│ │ └─┬POST
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (208932:9)
│ ├─┬/orgs/{org}/members/{username}/codespaces
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (208062:9)
│ ├─┬/repos/{owner}/{repo}/codespaces
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         └──[M] value (214900:9)
│ │ └─┬POST
│ │   └─┬Responses
│ │     ├─┬201
│ │     │ └─┬application/json
│ │     │   └─┬default
│ │     │     └──[M] value (208932:9)
│ │     └─┬202
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (208932:9)
│ ├─┬/user/codespaces/{codespace_name}/stop
│ │ └─┬POST
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (208932:9)
│ ├─┬/orgs/{org}/actions/secrets/{secret_name}
│ │ └─┬PUT
│ │   └──[M] description (4768:20)
│ ├─┬/repos/{owner}/{repo}/codespaces/machines
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (215186:9)
│ ├─┬/repos/{owner}/{repo}/git/trees/{tree_sha}
│ │ └─┬GET
│ │   ├──[M] description (26247:20)
│ │   └─┬Parameters
│ │     └──[-] description (25840:22)
│ ├─┬/user/codespaces/{codespace_name}
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         └──[M] value (208932:9)
│ │ └─┬PATCH
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (208932:9)
│ ├─┬/repos/{owner}/{repo}/dependabot/secrets/{secret_name}
│ │ └─┬PUT
│ │   └──[M] description (23793:20)
│ ├─┬/user/codespaces
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         └──[M] value (208062:9)
│ │ └─┬POST
│ │   └─┬Responses
│ │     ├─┬201
│ │     │ └─┬application/json
│ │     │   └─┬default
│ │     │     └──[M] value (208932:9)
│ │     └─┬202
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (208932:9)
│ ├─┬/repos/{owner}/{repo}/actions/secrets/{secret_name}
│ │ └─┬PUT
│ │   └──[M] description (16361:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/codespaces
│ │ └─┬POST
│ │   └─┬Responses
│ │     ├─┬202
│ │     │ └─┬application/json
│ │     │   └─┬default
│ │     │     └──[M] value (208932:9)
│ │     └─┬201
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (208932:9)
│ ├─┬/user/codespaces/{codespace_name}/start
│ │ └─┬POST
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (208932:9)
│ ├─┬/user/codespaces/secrets/{secret_name}
│ │ └─┬PUT
│ │   └──[M] description (38847:20)
│ └─┬/user/codespaces/{codespace_name}/machines
│   └─┬GET
│     └─┬Responses
│       └─┬200
│         └─┬application/json
│           └─┬default
│             └──[M] value (215186:9)
└─┬Components
  ├──[-] schemas (90080:7)❌
  ├──[-] schemas (125670:7)❌
  ├──[-] schemas (198026:7)❌
  ├──[-] schemas (198074:7)❌
  ├──[-] schemas (123434:7)❌
  ├──[-] schemas (91694:7)❌
  ├──[-] schemas (90887:7)❌
  ├──[-] schemas (198050:7)❌
  ├─┬api-overview
  │ └──[-] properties (64230:9)❌
  └─┬codespace-machine
    ├─┬display_name
    │ └──[M] examples (65898:13)
    └─┬memory_in_bytes
      └──[M] examples (65913:13)

Date: 08/10/23 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 42            | 1
components       | 11            | 9
❌  10 Breaking changes out of 53
INFO: Modifications: 41
INFO: Removals: 20
INFO: Breaking Removals: 18

ERROR: breaking changes discovered