[GitHub] Update to 1.1.4-6edac6ad28d0936afe65460dc8c6732f from 1.1.4-89579af3f1f5255ac2c758a7d1d6bcae Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit fd1b2c
                                                                                SPEC: extracted 2 commits from history

```
├─┬Paths
│ └─┬/orgs/{org}/properties/schema/{custom_property_name}
│   └─┬PUT
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └─┬default_value
│             ├──[🔀] type (11087:19)❌
│             ├──[➖] oneOf (11087:21)❌
│             └──[➖] oneOf (11088:21)❌
└─┬Components
  ├─┬org-custom-property
  │ └─┬default_value
  │   ├──[🔀] type (70565:11)❌
  │   ├──[➖] oneOf (70571:13)❌
  │   └──[➖] oneOf (70572:13)❌
  └─┬repository-rule-params-code-scanning-tool
    ├─┬alerts_threshold
    │ └──[🔀] description (71810:24)
    └─┬security_alerts_threshold
      └──[🔀] description (71819:24)

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 3             | 3                |
| components       | 5             | 3                |

Date: 04/06/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _8_
- **Modifications**: _4_
- **Removals**: _4_
- **Breaking Removals**: _4_
- **Breaking Modifications**: _2_

ERROR: breaking changes discovered