[GitHub] Update to 1.1.4-aa63f302adc26a9e08f80df72324f0dd from 1.1.4-77f428b6792170784451c1bba9fcab99 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 9a1c93
                                                                                SPEC: extracted 2 commits from history
                                                                                DONE: completed

├──[-] webhooks (60040:5)❌
├─┬Paths
│ ├──[-] path (31851:3)❌
│ ├──[-] path (31885:3)❌
│ ├──[-] path (31772:3)❌
│ ├──[+] path (31611:3)
│ ├─┬/gists/{gist_id}/comments
│ │ ├─┬GET
│ │ │ └──[-] description (1997:20)
│ │ └─┬POST
│ │   └──[-] description (2042:20)
│ ├─┬/repos/{owner}/{repo}/pulls
│ │ ├─┬GET
│ │ │ └──[M] description (31991:20)
│ │ └─┬POST
│ │   └──[M] description (32083:20)
│ ├─┬/gists/{gist_id}/comments/{comment_id}
│ │ ├─┬GET
│ │ │ └──[-] description (2106:20)
│ │ └─┬PATCH
│ │   └──[-] description (2145:20)
│ ├─┬/repos/{owner}/{repo}/readme/{dir}
│ │ └─┬GET
│ │   └──[M] description (33875:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/comments/{comment_id}/replies
│ │ └─┬POST
│ │   └──[M] description (32911:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/reviews/{review_id}
│ │ ├─┬GET
│ │ │ └──[M] description (33491:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (33522:20)
│ │ └─┬DELETE
│ │   └──[M] description (33570:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/analyses/{analysis_id}
│ │ └─┬GET
│ │   └──[M] description (21790:20)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/comments
│ │ ├─┬GET
│ │ │ └──[M] description (29578:20)
│ │ └─┬POST
│ │   └──[M] description (29621:20)
│ ├─┬/orgs/{org}/issues
│ │ └─┬GET
│ │   └──[M] description (8298:20)
│ ├─┬/repos/{owner}/{repo}/compare/{basehead}
│ │ └─┬GET
│ │   └──[M] description (24185:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/comments
│ │ ├─┬GET
│ │ │ └──[M] description (32721:20)
│ │ └─┬POST
│ │   ├──[M] description (32768:20)
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬position
│ │           └──[M] description (32808:32)
│ ├─┬/repos/{owner}/{repo}/stargazers
│ │ └─┬GET
│ │   └──[M] description (35787:20)
│ ├─┬/issues
│ │ └─┬GET
│ │   └──[M] description (2582:20)
│ ├─┬/users/{username}/starred
│ │ └─┬GET
│ │   └──[M] description (45191:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/reviews/{review_id}/dismissals
│ │ └─┬PUT
│ │   └──[M] description (33644:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/reviews
│ │ ├─┬GET
│ │ │ └──[M] description (33336:20)
│ │ └─┬POST
│ │   ├──[M] description (33371:20)
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬comments
│ │           └─┬Schema
│ │             └─┬position
│ │               └──[M] description (33431:38)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/commits
│ │ └─┬GET
│ │   └──[M] description (32969:20)
│ ├─┬/repos/{owner}/{repo}/pulls/comments
│ │ └─┬GET
│ │   └──[M] description (32187:20)
│ ├─┬/gists/{gist_id}/{sha}
│ │ └─┬GET
│ │   └──[-] description (2431:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/files
│ │ └─┬GET
│ │   └──[M] description (33008:20)
│ ├─┬/repos/{owner}/{repo}/git/blobs/{file_sha}
│ │ └─┬GET
│ │   └──[M] description (26563:20)
│ ├─┬/repos/{owner}/{repo}/contents/{path}
│ │ └─┬GET
│ │   └──[M] description (24276:20)
│ ├─┬/repos/{owner}/{repo}/commits/{commit_sha}/comments
│ │ ├─┬GET
│ │ │ └──[M] description (23717:20)
│ │ └─┬POST
│ │   └──[M] description (23753:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/reviews/{review_id}/events
│ │ └─┬POST
│ │   └──[M] description (33703:20)
│ ├─┬/gists/{gist_id}
│ │ ├─┬GET
│ │ │ └──[-] description (1831:20)
│ │ └─┬PATCH
│ │   └──[M] description (1863:20)
│ ├─┬/repos/{owner}/{repo}/issues/comments
│ │ └─┬GET
│ │   └──[M] description (28877:20)
│ ├─┬/repos/{owner}/{repo}/pulls/comments/{comment_id}
│ │ ├─┬GET
│ │ │ └──[M] description (32242:20)
│ │ └─┬PATCH
│ │   └──[M] description (32272:20)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}
│ │ ├─┬GET
│ │ │ └──[M] description (29254:20)
│ │ └─┬PATCH
│ │   └──[M] description (29301:20)
│ ├─┬/repos/{owner}/{repo}/comments
│ │ └─┬GET
│ │   └──[M] description (23291:20)
│ ├─┬/repos/{owner}/{repo}/commits/{ref}
│ │ └─┬GET
│ │   └──[M] description (23863:20)
│ ├─┬/user/starred
│ │ └─┬GET
│ │   └──[M] description (43770:20)
│ ├─┬/repos/{owner}/{repo}/issues
│ │ ├─┬GET
│ │ │ └──[M] description (28653:20)
│ │ └─┬POST
│ │   └──[M] description (28752:20)
│ ├─┬/repos/{owner}/{repo}/comments/{comment_id}
│ │ ├─┬GET
│ │ │ └──[-] description (23394:20)
│ │ └─┬PATCH
│ │   └──[-] description (23432:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/reviews/{review_id}/comments
│ │ └─┬GET
│ │   └──[M] description (33605:20)
│ ├─┬/repos/{owner}/{repo}/license
│ │ └─┬GET
│ │   └──[M] description (30695:20)
│ ├─┬/gitignore/templates/{name}
│ │ └─┬GET
│ │   └──[M] description (2469:20)
│ ├─┬/user/issues
│ │ └─┬GET
│ │   └──[M] description (41733:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}
│ │ ├─┬GET
│ │ │ └──[M] description (32487:20)
│ │ └─┬PATCH
│ │   └──[M] description (32539:20)
│ ├─┬/repos/{owner}/{repo}/readme
│ │ └─┬GET
│ │   └──[M] description (33833:20)
│ └─┬/repos/{owner}/{repo}/issues/comments/{comment_id}
│   ├─┬GET
│   │ └──[M] description (28930:20)
│   └─┬PATCH
│     └──[M] description (28961:20)
└─┬Components
  ├──[-] parameters (237313:7)❌
  ├──[-] examples (227731:7)❌
  ├──[-] schemas (199871:7)❌
  ├──[-] schemas (82396:7)❌
  ├─┬secret-scanning-alert-webhook
  │ └──[-] properties (89189:9)❌
  ├─┬page-deployment
  │ └─┬status_url
  │   └──[M] examples (81883:13)
  ├─┬webhook-github-app-authorization-revoked
  │ ├──[+] properties (101229:9)
  │ ├──[+] properties (101231:9)
  │ ├──[+] properties (101233:9)
  │ └──[+] properties (101235:9)
  ├─┬rule-suite
  │ ├─┬actor_id
  │ │ └──[M] type (71529:17)❌
  │ └─┬actor_name
  │   └──[M] type (71532:17)❌
  └─┬custom-property-value
    └─┬value
      ├──[M] type (70236:11)❌
      ├──[-] oneOf (70722:13)❌
      └──[-] oneOf (70723:13)❌

Date: 01/25/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 62            | 3
components       | 15            | 10

❌  13 Breaking changes out of 77
INFO: Modifications: 54
INFO: Removals: 19
INFO: Additions: 5
INFO: Breaking Removals: 11
INFO: Breaking Modifications: 3

ERROR: breaking changes discovered