[GitHub] Update to 1.1.4-356ea13d8867f0f4f84319bdf06dc720 from 1.1.4-0479485a780820e347c408d64af6de00 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit f200cb
                                                                                SPEC: extracted 2 commits from history

```
├─┬Paths
│ ├──[➖] path (6457:3)❌
│ ├──[➖] path (6233:3)❌
│ ├──[➖] path (6597:3)❌
│ ├──[➖] path (6271:3)❌
│ ├──[➖] path (6521:3)❌
│ ├──[➖] path (6050:3)❌
│ └─┬/enterprises/{enterprise}/copilot/billing/seats
│   └─┬GET
│     ├──[🔀] description (1428:20)
│     └─┬Responses
│       └─┬200
│         └─┬application/json
│           └─┬Schema
│             └─┬total_seats
│               └──[🔀] description (1462:34)
└─┬Components
  ├──[➖] parameters (221435:7)❌
  ├──[➖] examples (200226:7)❌
  ├──[➖] examples (200280:7)❌
  ├──[➖] examples (200262:7)❌
  ├──[➖] examples (200337:7)❌
  ├──[➖] examples (200319:7)❌
  ├──[➖] schemas (70447:7)❌
  ├──[➖] schemas (70536:7)❌
  ├──[➖] schemas (70551:7)❌
  ├─┬webhook-branch-protection-rule-edited
  │ └─┬changes
  │   ├──[➖] properties (99319:13)❌
  │   ├──[➖] properties (99308:13)❌
  │   ├──[➖] properties (99328:13)❌
  │   └──[➖] properties (99339:13)❌
  └─┬webhooks_rule
    ├──[➖] required (90419:9)❌
    ├──[➖] properties (90340:9)❌
    └──[➖] properties (90331:9)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 8             | 6                |
| components       | 16            | 16               |

Date: 06/21/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _22_ out of _24_
- **Modifications**: _2_
- **Removals**: _22_
- **Breaking Removals**: _22_

ERROR: breaking changes discovered