[GitHub] Update to 1.1.4-1a5c27df40e2c66ac3dac2b39c0e601b from 1.1.4-f8cf9b6b12b5036930560db0c2532fe8 Detected Schema changes:
├─┬Paths
│ ├─┬/orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}
│ │ └─┬GET
│ │   └──[M] description (12990:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}/instances
│ │ └─┬GET
│ │   └──Parameters
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts
│ │ └─┬GET
│ │   └──Parameters
│ ├─┬/repos/{owner}/{repo}/code-scanning/sarifs
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         ├──[-] additionalProperties (21554:37)❌
│ │         └─┬ref
│ │           └──[M] $ref (67499:13)❌
│ └─┬/repos/{owner}/{repo}/code-scanning/analyses
│   └─┬GET
│     └──Parameters
└─┬Components
  ├──[-] schemas (75592:7)❌
  └─┬code-scanning-ref
    └──[M] description (67500:20)

Date: 11/15/23 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 3             | 2
components       | 2             | 1

❌  3 Breaking changes out of 5
INFO: Modifications: 3
INFO: Removals: 2
INFO: Breaking Removals: 2
INFO: Breaking Modifications: 1

ERROR: breaking changes discovered