[GitHub] Update to 1.1.4-4443d2c21890f0b754f9e632d191bd85 from 1.1.4-758801dbed7c532f009e5f428e0454a9 Detected Schema changes:
```
├──[➖] webhooks (63440:5)❌
├─┬Paths
│ ├─┬/orgs/{org}/secret-scanning/alerts
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[🔀] description (226261:20)
│ ├─┬/enterprises/{enterprise}/secret-scanning/alerts
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[🔀] description (226261:20)
│ └─┬/repos/{owner}/{repo}/secret-scanning/alerts
│   └─┬GET
│     └─┬Parameters
│       └──[🔀] description (226261:20)
└─┬Components
  └──[➖] schemas (191790:7)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 3             | 0                |
| components       | 1             | 1                |

Date: 12/13/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _1_ out of _4_
- **Modifications**: _3_
- **Removals**: _2_
- **Breaking Removals**: _2_

ERROR: breaking changes discovered