[GitHub] Update to 1.1.4-97ae665c50dc0af2640cf572009dd76b from 1.1.4-356ea13d8867f0f4f84319bdf06dc720 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 2c2b80
```
                                                                                SPEC: extracted 2 commits from history
├─┬Paths
│ ├──[➖] path (45944:3)❌
│ ├──[➖] path (19370:3)❌
│ ├──[➖] path (19442:3)❌
│ └──[➖] path (5875:3)❌
└─┬Components
  ├──[➖] examples (206045:7)❌
  ├──[➖] examples (200322:7)❌
  └──[➖] schemas (89415:7)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 4             | 4                |
| components       | 3             | 3                |

Date: 06/22/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _7_ out of _7_
- **Removals**: _7_
- **Breaking Removals**: _7_

ERROR: breaking changes discovered