[GitHub] Update to 1.1.4-a359c50c42a91cee9b6aa2cfcf93605d from 1.1.4-f0ef821141c0585bc8759f53f482f086 Detected Schema changes:
```
├─┬Paths
│ ├──[➖] path (5043:3)❌
│ ├──[➖] path (4956:3)❌
│ ├──[➖] path (4691:3)❌
│ ├──[➖] path (5182:3)❌
│ ├──[➖] path (5092:3)❌
│ ├──[➖] path (4827:3)❌
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts
│ │ └─┬GET
│ │   ├──[➖] parameters (223851:13)❌
│ │   └──[➖] parameters (223842:13)❌
│ └─┬/repos/{owner}/{repo}
│   └─┬PATCH
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └─┬security_and_analysis
│             └──[➖] properties (16765:21)❌
└─┬Components
  ├──[➖] parameters (224234:7)❌
  ├──[➖] parameters (224227:7)❌
  ├──[➖] examples (202345:7)❌
  ├──[➖] examples (202292:7)❌
  ├──[➖] examples (202329:7)❌
  ├──[➖] schemas (71656:7)❌
  ├─┬repository-ruleset
  │ └─┬_links
  │   └─┬html
  │     └──[🔀] type (74833:21)❌
  └─┬security-and-analysis
    └──[➖] properties (70683:9)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 9             | 9                |
| components       | 8             | 8                |

Date: 10/18/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _17_ out of _17_
- **Modifications**: _1_
- **Removals**: _16_
- **Breaking Removals**: _16_
- **Breaking Modifications**: _1_

ERROR: breaking changes discovered