[GitHub] Update to 1.1.4-10709c2cd95791d7429380234be06a83 from 1.1.4-7175787c7e49e097149d5858b6551438 Detected Schema changes:
```
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/security-advisories/reports
│ │ └─┬POST
│ │   └─┬Responses
│ │     └─┬201
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[🔀] value (217403:9)
│ │           ├──[🔀] value (217403:9)
│ │           ├──[🔀] value (217403:9)
│ │           ├──[🔀] value (217403:9)
│ │           ├──[🔀] value (217403:9)
│ │           ├──[🔀] value (217403:9)
│ │           ├──[🔀] value (217403:9)
│ │           ├──[🔀] value (217403:9)
│ │           ├──[🔀] value (217403:9)
│ │           ├──[🔀] value (217403:9)
│ │           ├──[🔀] value (217403:9)
│ │           ├──[🔀] value (217403:9)
│ │           ├──[🔀] value (217403:9)
│ │           ├──[🔀] value (217403:9)
│ │           ├──[🔀] value (217403:9)
│ │           ├──[🔀] value (217403:9)
│ │           ├──[🔀] value (217403:9)
│ │           └──[➖] value (217537:9)
│ ├─┬/repos/{owner}/{repo}/dependabot/alerts/{alert_number}
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         └──[🔀] value (212111:9)
│ │ └─┬PATCH
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (212188:9)
│ ├─┬/repos/{owner}/{repo}/security-advisories
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         └──[🔀] value (205034:7)
│ │ └─┬POST
│ │   └─┬Responses
│ │     └─┬201
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[🔀] value (217198:9)
│ │           ├──[🔀] value (217198:9)
│ │           ├──[🔀] value (217198:9)
│ │           ├──[🔀] value (217198:9)
│ │           ├──[🔀] value (217198:9)
│ │           ├──[🔀] value (217198:9)
│ │           ├──[🔀] value (217198:9)
│ │           ├──[🔀] value (217198:9)
│ │           ├──[🔀] value (217198:9)
│ │           ├──[🔀] value (217198:9)
│ │           ├──[🔀] value (217198:9)
│ │           ├──[🔀] value (217198:9)
│ │           ├──[🔀] value (217198:9)
│ │           ├──[🔀] value (217198:9)
│ │           ├──[🔀] value (217198:9)
│ │           ├──[🔀] value (217198:9)
│ │           ├──[🔀] value (217198:9)
│ │           └──[➖] value (217325:9)
│ ├─┬/repos/{owner}/{repo}/security-advisories/{ghsa_id}
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         ├──[🔀] value (217198:9)
│ │ │         ├──[🔀] value (217198:9)
│ │ │         ├──[🔀] value (217198:9)
│ │ │         ├──[🔀] value (217198:9)
│ │ │         ├──[🔀] value (217198:9)
│ │ │         ├──[🔀] value (217198:9)
│ │ │         ├──[🔀] value (217198:9)
│ │ │         ├──[🔀] value (217198:9)
│ │ │         ├──[🔀] value (217198:9)
│ │ │         ├──[🔀] value (217198:9)
│ │ │         ├──[🔀] value (217198:9)
│ │ │         ├──[🔀] value (217198:9)
│ │ │         ├──[🔀] value (217198:9)
│ │ │         ├──[🔀] value (217198:9)
│ │ │         ├──[🔀] value (217198:9)
│ │ │         ├──[🔀] value (217198:9)
│ │ │         ├──[🔀] value (217198:9)
│ │ │         └──[➖] value (217325:9)
│ │ └─┬PATCH
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         ├─┬add_credit
│ │         │ ├──[🔀] value (217198:9)
│ │         │ ├──[🔀] value (217198:9)
│ │         │ ├──[🔀] value (217198:9)
│ │         │ ├──[🔀] value (217198:9)
│ │         │ ├──[🔀] value (217198:9)
│ │         │ ├──[🔀] value (217198:9)
│ │         │ ├──[🔀] value (217198:9)
│ │         │ ├──[🔀] value (217198:9)
│ │         │ ├──[🔀] value (217198:9)
│ │         │ ├──[🔀] value (217198:9)
│ │         │ ├──[🔀] value (217198:9)
│ │         │ ├──[🔀] value (217198:9)
│ │         │ ├──[🔀] value (217198:9)
│ │         │ ├──[🔀] value (217198:9)
│ │         │ ├──[🔀] value (217198:9)
│ │         │ ├──[🔀] value (217198:9)
│ │         │ ├──[🔀] value (217198:9)
│ │         │ └──[➖] value (217325:9)
│ │         └─┬default
│ │           ├──[🔀] value (217198:9)
│ │           ├──[🔀] value (217198:9)
│ │           ├──[🔀] value (217198:9)
│ │           ├──[🔀] value (217198:9)
│ │           ├──[🔀] value (217198:9)
│ │           ├──[🔀] value (217198:9)
│ │           ├──[🔀] value (217198:9)
│ │           ├──[🔀] value (217198:9)
│ │           ├──[🔀] value (217198:9)
│ │           ├──[🔀] value (217198:9)
│ │           ├──[🔀] value (217198:9)
│ │           ├──[🔀] value (217198:9)
│ │           ├──[🔀] value (217198:9)
│ │           ├──[🔀] value (217198:9)
│ │           ├──[🔀] value (217198:9)
│ │           ├──[🔀] value (217198:9)
│ │           ├──[🔀] value (217198:9)
│ │           └──[➖] value (217325:9)
│ ├─┬/enterprises/{enterprise}/dependabot/alerts
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (199498:7)
│ ├─┬/orgs/{org}/security-advisories
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (205034:7)
│ ├─┬/advisories/{ghsa_id}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[🔀] value (196689:9)
│ │           ├──[🔀] value (196689:9)
│ │           ├──[🔀] value (196689:9)
│ │           ├──[🔀] value (196689:9)
│ │           ├──[🔀] value (196689:9)
│ │           ├──[🔀] value (196689:9)
│ │           ├──[🔀] value (196689:9)
│ │           ├──[🔀] value (196689:9)
│ │           ├──[🔀] value (196689:9)
│ │           ├──[🔀] value (196689:9)
│ │           ├──[🔀] value (196689:9)
│ │           ├──[🔀] value (196689:9)
│ │           ├──[🔀] value (196689:9)
│ │           ├──[🔀] value (196689:9)
│ │           ├──[🔀] value (196689:9)
│ │           ├──[🔀] value (196689:9)
│ │           ├──[🔀] value (196689:9)
│ │           ├──[🔀] value (196689:9)
│ │           └──[➖] value (196753:9)
│ ├─┬/advisories
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (196625:7)
│ ├─┬/repos/{owner}/{repo}/dependabot/alerts
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (211944:7)
│ └─┬/orgs/{org}/dependabot/alerts
│   └─┬GET
│     └─┬Responses
│       └─┬200
│         └─┬application/json
│           └─┬default
│             └──[🔀] value (199498:7)
└─┬Components
  ├──[➖] schemas (64458:7)❌
  ├─┬global-advisory
  │ └──[➖] properties (64791:9)❌
  ├─┬repository-advisory
  │ └──[➖] properties (75229:9)❌
  ├─┬webhooks_security_advisory
  │ └──[➖] properties (100193:9)❌
  ├─┬webhook-security-advisory-withdrawn
  │ └─┬security_advisory
  │   └──[➖] properties (189400:13)❌
  └─┬dependabot-alert-security-advisory
    └──[➖] properties (67798:9)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 117           | 0                |
| components       | 6             | 6                |

Date: 09/16/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _6_ out of _123_
- **Modifications**: _111_
- **Removals**: _12_
- **Breaking Removals**: _6_

ERROR: breaking changes discovered