[GitHub] Update to 1.1.4-a0f103fbdfbd51bde7455e34664c5ba3 from 1.1.4-c956dacd1ed3014e8efb91f1eb6a337d Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 9c87ec
                                                                                SPEC: extracted 2 commits from history

```
├─┬Paths
│ ├──[➕] path (10222:3)
│ ├─┬/repos/{owner}/{repo}/rulesets/rule-suites
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[🔀] description (223402:20)
│ ├─┬/orgs/{org}/organization-roles/{role_id}/users
│ │ └─┬GET
│ │   └──[🔀] description (10783:20)
│ ├─┬/orgs/{org}/organization-roles/teams/{team_slug}
│ │ └─┬DELETE
│ │   └──[🔀] description (10412:20)
│ ├─┬/orgs/{org}/rulesets/rule-suites
│ │ └─┬GET
│ │   └──[➖] parameters (222604:13)❌
│ ├─┬/orgs/{org}/organization-roles/users/{username}
│ │ └─┬DELETE
│ │   └──[🔀] description (10496:20)
│ ├─┬/orgs/{org}/organization-roles/{role_id}
│ │ ├──[➕] delete (10707:7)
│ │ ├──[➕] patch (10619:7)
│ │ └─┬GET
│ │   └──[🔀] description (10581:20)
│ ├─┬/orgs/{org}/organization-roles/{role_id}/teams
│ │ └─┬GET
│ │   └──[🔀] description (10737:20)
│ ├─┬/repos/{owner}/{repo}/git/commits
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬parents
│ │           └──[🔀] description (28637:32)
│ ├─┬/orgs/{org}/organization-roles/users/{username}/{role_id}
│ │ ├─┬PUT
│ │ │ └──[🔀] description (10522:20)
│ │ └─┬DELETE
│ │   └──[🔀] description (10554:20)
│ ├─┬/orgs/{org}/organization-roles/teams/{team_slug}/{role_id}
│ │ ├─┬PUT
│ │ │ └──[🔀] description (10438:20)
│ │ └─┬DELETE
│ │   └──[🔀] description (10469:20)
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment_protection_rules/apps
│ │ └─┬GET
│ │   └──[🔀] description (27790:20)
│ └─┬/orgs/{org}/organization-roles
│   ├──[➕] post (10315:7)
│   └─┬GET
│     └──[🔀] description (10268:20)
└─┬Components
  ├──[➕] examples (203261:7)
  ├──[➕] schemas (72132:7)
  └─┬environment
    └─┬id
      └──[➖] format (81743:19)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 18            | 1                |
| components       | 3             | 1                |

Date: 07/19/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _2_ out of _21_
- **Modifications**: _13_
- **Removals**: _2_
- **Additions**: _6_
- **Breaking Removals**: _2_

ERROR: breaking changes discovered