[GitHub] Update to 1.1.4-89579af3f1f5255ac2c758a7d1d6bcae from 1.1.4-3fc5da0b62540a45f2138abebf230a76 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 9fcfbe
                                                                                SPEC: extracted 2 commits from history

```
├─┬Paths
│ └─┬/orgs/{org}
│   ├─┬GET
│   │ └──[🔀] description (3674:20)
│   └─┬PATCH
│     ├──[🔀] description (3711:20)
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └─┬description
│             └──[🔀] description (3754:32)
└─┬Components
  ├──[➖] schemas (71803:7)❌
  └──[➕] schemas (71780:7)

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 3             | 0                |
| components       | 2             | 1                |

Date: 04/04/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _5_
- **Modifications**: _3_
- **Removals**: _1_
- **Additions**: _1_
- **Breaking Removals**: _1_

ERROR: breaking changes discovered