[GitHub] Update to 1.1.4-95c17fdaedbd73d404bbf04c1d953250 from 1.1.4-ce11a30340deb9560fca3f8049e3f57b Detected Schema changes:
```
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/actions/runs/{run_id}/artifacts
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (213139:9)
│ ├─┬/repos/{owner}/{repo}/actions/artifacts/{artifact_id}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[🔀] value (213175:9)
│ │           ├──[🔀] value (213175:9)
│ │           ├──[🔀] value (213175:9)
│ │           ├──[🔀] value (213175:9)
│ │           ├──[🔀] value (213175:9)
│ │           ├──[🔀] value (213175:9)
│ │           ├──[🔀] value (213175:9)
│ │           ├──[🔀] value (213175:9)
│ │           ├──[🔀] value (213175:9)
│ │           └──[➖] value (213186:9)
│ └─┬/repos/{owner}/{repo}/actions/artifacts
│   └─┬GET
│     └─┬Responses
│       └─┬200
│         └─┬application/json
│           └─┬default
│             └──[🔀] value (213139:9)
└─┬Components
  └─┬artifact
    └──[➖] properties (81816:9)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 12            | 0                |
| components       | 1             | 1                |

Date: 02/21/25 | Commit: Original: etc/specs/GitHub/current.spec.yaml, Modified: etc/specs/GitHub/previous.spec.yaml,

- ❌ **BREAKING Changes**: _1_ out of _13_
- **Modifications**: _11_
- **Removals**: _2_
- **Breaking Removals**: _1_

ERROR: breaking changes discovered