[GitHub] Update to 1.1.4-f0ef821141c0585bc8759f53f482f086 from 1.1.4-c6249831ad99957f8d160f21b8d426dd Detected Schema changes:
```
├─┬Paths
│ ├─┬/orgs/{org}/rulesets
│ │ └─┬GET
│ │   └──[➖] parameters (223775:13)❌
│ └─┬/repos/{owner}/{repo}/rulesets
│   └─┬GET
│     └──[➖] parameters (223775:13)❌
└─┬Components
  ├──[➖] parameters (223775:7)❌
  └─┬organization-full
    └──[➕] properties (70755:9)

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 2             | 2                |
| components       | 2             | 1                |

Date: 10/10/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _3_ out of _4_
- **Removals**: _3_
- **Additions**: _1_
- **Breaking Removals**: _3_

ERROR: breaking changes discovered