[GitHub] Update to 1.1.4-dbba2c62a8f04380c590a1aa0d1194e8 from 1.1.4-2c0c305301b4db15047c06c5d15a3675 Detected Schema changes:
```
├─┬Paths
│ ├─┬/orgs/{org}/attestations/{subject_digest}
│ │ └─┬GET
│ │   └──[➖] parameters (7550:15)❌
│ ├─┬/users/{username}/attestations/{subject_digest}
│ │ └─┬GET
│ │   ├──[➖] parameters (49825:15)❌
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         ├─┬Schema
│ │         │ └─┬attestations
│ │         │   └─┬Schema
│ │         │     └─┬bundle
│ │         │       └──[🔀] $ref (94888:14)❌
│ │         └─┬default
│ │           └──[🔀] value (49830:25)
│ └─┬/repos/{owner}/{repo}/attestations/{subject_digest}
│   └─┬GET
│     └──[➖] parameters (22493:15)❌
└─┬Components
  ├──[➕] schemas (94888:7)
  └─┬repository-rule-pull-request
    └─┬parameters
      └─┬allowed_merge_methods
        └──[🔀] description (79146:28)

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 5             | 4                |
| components       | 2             | 0                |

Date: 02/28/25 | Commit: Original: etc/specs/GitHub/current.spec.yaml, Modified: etc/specs/GitHub/previous.spec.yaml,

- ❌ **BREAKING Changes**: _4_ out of _7_
- **Modifications**: _3_
- **Removals**: _3_
- **Additions**: _1_
- **Breaking Removals**: _3_
- **Breaking Modifications**: _1_

ERROR: breaking changes discovered