[GitHub] Update to 1.1.4-ee410229436a838f44c982a4ed9c9572 from 1.1.4-4443d2c21890f0b754f9e632d191bd85 Detected Schema changes:
```
├─┬Paths
│ ├──[➖] path (24595:3)❌
│ ├──[➖] path (24501:3)❌
│ ├──[➖] path (1656:3)❌
│ ├──[➖] path (1436:3)❌
│ ├──[➖] path (2052:3)❌
│ ├──[➖] path (1688:3)❌
│ ├──[➖] path (1919:3)❌
│ ├──[➖] path (1976:3)❌
│ ├─┬/orgs/{org}/security-managers/teams/{team_slug}
│ │ ├─┬PUT
│ │ │ ├──[🔀] description (13840:20)
│ │ │ ├──[➖] deprecated (14542:19)
│ │ │ └─┬Extensions
│ │ │   └──[🔀] x-github (13859:9)
│ │ └─┬DELETE
│ │   ├──[🔀] description (13866:20)
│ │   ├──[➖] deprecated (14568:19)
│ │   └─┬Extensions
│ │     └──[🔀] x-github (13885:9)
│ └─┬/orgs/{org}/security-managers
│   └─┬GET
│     ├──[🔀] description (13805:20)
│     ├──[➖] deprecated (14515:19)
│     └─┬Extensions
│       └──[🔀] x-github (13832:9)
└─┬Components
  ├──[➖] responses (228850:7)❌
  ├──[➖] responses (228841:7)❌
  ├──[➖] examples (213538:7)❌
  ├──[➖] examples (202960:7)❌
  ├──[➖] examples (213529:7)❌
  ├──[➖] examples (213524:7)❌
  ├──[➖] examples (213519:7)❌
  ├──[➖] examples (202906:7)❌
  ├──[➖] examples (213534:7)❌
  ├──[➖] schemas (82818:7)❌
  ├──[➖] schemas (82836:7)❌
  ├──[➖] schemas (82826:7)❌
  ├──[➖] schemas (82831:7)❌
  ├──[➖] schemas (82863:7)❌
  ├──[➖] schemas (82849:7)❌
  └─┬api-overview
    └─┬domains
      └──[➖] properties (72096:13)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 17            | 8                |
| components       | 16            | 16               |

Date: 12/16/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _24_ out of _33_
- **Modifications**: _6_
- **Removals**: _27_
- **Breaking Removals**: _24_

ERROR: breaking changes discovered