[GitHub] Update to 1.1.4-9cd6c8e7bead01c0c83af26875ff027b from 1.1.4-d8074bd9e0c6a1faac9d78d77016fd5e Detected Schema changes:
```
├─┬Paths
│ ├──[➖] path (40932:3)❌
│ ├──[➖] path (15284:3)❌
│ ├──[➖] path (40974:3)❌
│ ├──[➖] path (15243:3)❌
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/reactions
│ │ └─┬POST
│ │   └─┬Extensions
│ │     └──[🔀] x-github (35354:9)
│ ├─┬/repos/{owner}/{repo}/actions/runs/{run_id}/timing
│ │ └─┬GET
│ │   └──[🔀] description (21382:20)
│ └─┬/repos/{owner}/{repo}/actions/workflows/{workflow_id}/timing
│   └─┬GET
│     └──[🔀] description (22072:20)
└─┬Components
  ├──[➖] examples (223443:7)❌
  ├──[➖] examples (211287:7)❌
  ├──[➖] examples (211270:7)❌
  ├──[➖] schemas (79831:7)❌
  └──[➖] schemas (79854:7)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 7             | 4                |
| components       | 5             | 5                |

Date: 02/11/25 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _9_ out of _12_
- **Modifications**: _3_
- **Removals**: _9_
- **Breaking Removals**: _9_

ERROR: breaking changes discovered