[GitHub] Update to 1.1.4-b29f0a104a78b31f92c3c5617714fccf from 1.1.4-4f074e36604109b0a5cfe5fde6c79805 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit b93abb
                                                                                SPEC: extracted 2 commits from history
                                                                                DONE: completed

├─┬Paths
│ └─┬/repos/{owner}/{repo}/autolinks
│   └─┬GET
│     ├──[+] parameters (236331:13)❌
│     ├──[M] summary (18374:16)
│     ├──[M] description (18375:20)
│     └─┬External Docs
│       └──[M] url (18384:14)
└─┬Components
  └──[-] schemas (71868:7)❌

Date: 02/02/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 4             | 1
components       | 1             | 1

❌  2 Breaking changes out of 5
INFO: Modifications: 3
INFO: Removals: 1
INFO: Additions: 1
INFO: Breaking Removals: 1
INFO: Breaking Additions: 1

ERROR: breaking changes discovered