[GitHub] Update to 1.1.4-3095567e16510823377396fa6baddc5a from 1.1.4-ac26bea3c7b43c61995d720fd1312db2 Detected Schema changes:
├─┬Paths
│ ├──[-] path (33710:3)❌
│ ├──[-] path (10696:3)❌
│ ├──[-] path (33670:3)❌
│ ├──[-] path (10657:3)❌
│ └─┬/markdown/raw
│   └──POST
└─┬Components
  ├──[-] parameters (234165:7)❌
  ├──[-] parameters (234195:7)❌
  ├──[-] parameters (234188:7)❌
  ├──[-] parameters (234208:7)❌
  ├──[-] parameters (234680:7)❌
  ├──[-] parameters (234172:7)❌
  ├──[-] examples (215154:7)❌
  ├──[-] examples (215131:7)❌
  ├──[-] schemas (69063:7)❌
  └──[-] schemas (69011:7)❌

Date: 09/29/23 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 4             | 4
components       | 10            | 10
❌  14 Breaking changes out of 14
INFO: Removals: 14
INFO: Breaking Removals: 14

ERROR: breaking changes discovered