[GitHub] Update to 1.1.4-ed9f9c8a528083c4f510bc9ec29e7cbc from 1.1.4-81b4fcdf6c7b3f61c17f56a0c4f2231d Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit b02b0b
                                                                                SPEC: extracted 2 commits from history

```
├─┬Paths
│ ├─┬/orgs/{org}/copilot/billing/selected_teams
│ │ └─┬POST
│ │   └──[🔀] description (7463:20)
│ ├─┬/orgs/{org}/security-managers/teams/{team_slug}
│ │ └─┬PUT
│ │   └─┬Responses
│ │     └──[➕] codes (13112:11)
│ ├─┬/orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}
│ │ └─┬PUT
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬permission
│ │           └──[➕] default (14779:28)❌
│ └─┬/orgs/{org}/copilot/billing/selected_users
│   └─┬POST
│     └──[🔀] description (7626:20)
└─┬Components
  ├─┬webhook-issues-transferred
  │ └─┬changes
  │   └─┬new_repository
  │     └─┬id
  │       └──[➖] format (125580:27)❌
  ├─┬webhook-fork
  │ └─┬forkee
  │   └─┬ALLOF
  │     └─┬id
  │       └──[➖] format (109699:25)❌
  ├─┬gpg-key
  │ ├─┬id
  │ │ └──[➖] format (89407:19)❌
  │ └─┬subkeys
  │   └─┬Schema
  │     └─┬id
  │       └──[➖] format (89447:25)❌
  ├─┬webhook-pull-request-review-thread-unresolved
  │ └─┬pull_request
  │   ├─┬base
  │   │ └─┬repo
  │   │   └─┬id
  │   │     └──[➖] format (173951:31)❌
  │   └─┬head
  │     └─┬repo
  │       └─┬id
  │         └──[➖] format (174526:31)❌
  ├─┬webhook-pull-request-synchronize
  │ └─┬pull_request
  │   ├─┬head
  │   │ └─┬repo
  │   │   └─┬id
  │   │     └──[➖] format (177006:31)❌
  │   └─┬base
  │     └─┬repo
  │       └─┬id
  │         └──[➖] format (176370:31)❌
  ├─┬webhook-pull-request-labeled
  │ └─┬pull_request
  │   ├─┬head
  │   │ └─┬repo
  │   │   └─┬id
  │   │     └──[➖] format (144035:31)❌
  │   └─┬base
  │     └─┬repo
  │       └─┬id
  │         └──[➖] format (143395:31)❌
  ├─┬simple-repository
  │ └─┬id
  │   └──[➖] format (67366:19)❌
  ├─┬webhook-team-removed-from-repository
  │ └─┬repository
  │   └─┬id
  │     └──[➖] format (191522:23)❌
  ├─┬webhook-pull-request-review-dismissed
  │ └─┬pull_request
  │   ├─┬head
  │   │ └─┬repo
  │   │   └─┬id
  │   │     └──[➖] format (155743:31)❌
  │   └─┬base
  │     └─┬repo
  │       └─┬id
  │         └──[➖] format (155116:31)❌
  ├─┬webhook-pull-request-unlocked
  │ └─┬pull_request
  │   ├─┬head
  │   │ └─┬repo
  │   │   └─┬id
  │   │     └──[➖] format (184001:31)❌
  │   └─┬base
  │     └─┬repo
  │       └─┬id
  │         └──[➖] format (183363:31)❌
  ├─┬migration
  │ └─┬id
  │   └──[➖] format (71924:19)❌
  ├─┬repository-webhooks
  │ └─┬id
  │   └──[➖] format (89978:19)❌
  ├─┬codespace-with-full-repository
  │ └─┬id
  │   └──[➖] format (89133:19)❌
  ├─┬webhook-team-created
  │ └─┬repository
  │   └─┬id
  │     └──[➖] format (189990:23)❌
  ├─┬webhook-pull-request-review-edited
  │ └─┬pull_request
  │   ├─┬base
  │   │ └─┬repo
  │   │   └─┬id
  │   │     └──[➖] format (157501:31)❌
  │   └─┬head
  │     └─┬repo
  │       └─┬id
  │         └──[➖] format (158069:31)❌
  ├─┬webhook-pull-request-locked
  │ └─┬pull_request
  │   ├─┬head
  │   │ └─┬repo
  │   │   └─┬id
  │   │     └──[➖] format (146372:31)❌
  │   └─┬base
  │     └─┬repo
  │       └─┬id
  │         └──[➖] format (145732:31)❌
  ├─┬webhook-pull-request-unassigned
  │ └─┬pull_request
  │   ├─┬base
  │   │ └─┬repo
  │   │   └─┬id
  │   │     └──[➖] format (178700:31)❌
  │   └─┬head
  │     └─┬repo
  │       └─┬id
  │         └──[➖] format (179340:31)❌
  ├─┬full-repository
  │ └─┬id
  │   └──[➖] format (72728:19)❌
  ├─┬enterprise-team
  │ └─┬id
  │   └──[➖] format (66903:19)❌
  ├─┬webhook-pull-request-dequeued
  │ └─┬pull_request
  │   ├─┬head
  │   │ └─┬repo
  │   │   └─┬id
  │   │     └──[➖] format (139312:31)❌
  │   └─┬base
  │     └─┬repo
  │       └─┬id
  │         └──[➖] format (138676:31)❌
  ├─┬webhook-pull-request-review-requested
  │ ├─┬ONEOF
  │ │ ├──[➕] required (166292:11)❌
  │ │ ├──[➖] required (168770:11)❌
  │ │ ├──[➕] properties (166219:11)
  │ │ ├──[➖] properties (168665:11)❌
  │ │ └─┬pull_request
  │ │   ├─┬requested_reviewers
  │ │   │ └─┬Schema
  │ │   │   └─┬ONEOF
  │ │   │     ├──[➕] required (165977:23)❌
  │ │   │     ├──[➕] required (165969:23)❌
  │ │   │     ├──[➕] required (165970:23)❌
  │ │   │     ├──[➕] required (165972:23)❌
  │ │   │     ├──[➕] required (165976:23)❌
  │ │   │     ├──[➕] required (165974:23)❌
  │ │   │     ├──[➕] required (165975:23)❌
  │ │   │     ├──[➕] required (165971:23)❌
  │ │   │     └──[➕] required (165973:23)❌
  │ │   ├─┬head
  │ │   │ └─┬repo
  │ │   │   └─┬id
  │ │   │     └──[➖] format (167511:33)❌
  │ │   └─┬base
  │ │     └─┬repo
  │ │       └─┬id
  │ │         └──[➖] format (166875:33)❌
  │ └─┬ONEOF
  │   ├──[➕] required (168716:11)❌
  │   ├──[➖] required (166344:11)❌
  │   ├──[➕] properties (168611:11)
  │   ├──[➖] properties (166271:11)❌
  │   └─┬pull_request
  │     ├─┬requested_reviewers
  │     │ └─┬Schema
  │     │   └─┬ONEOF
  │     │     ├──[➖] required (166027:23)❌
  │     │     ├──[➖] required (166023:23)❌
  │     │     ├──[➖] required (166024:23)❌
  │     │     ├──[➖] required (166025:23)❌
  │     │     ├──[➖] required (166026:23)❌
  │     │     ├──[➖] required (166021:23)❌
  │     │     ├──[➖] required (166022:23)❌
  │     │     ├──[➖] required (166028:23)❌
  │     │     └──[➖] required (166029:23)❌
  │     ├─┬base
  │     │ └─┬repo
  │     │   └─┬id
  │     │     └──[➖] format (164472:33)❌
  │     └─┬head
  │       └─┬repo
  │         └─┬id
  │           └──[➖] format (165108:33)❌
  ├─┬webhook-pull-request-review-submitted
  │ └─┬pull_request
  │   ├─┬head
  │   │ └─┬repo
  │   │   └─┬id
  │   │     └──[➖] format (169927:31)❌
  │   └─┬base
  │     └─┬repo
  │       └─┬id
  │         └──[➖] format (169298:31)❌
  ├─┬organization-invitation
  │ └─┬id
  │   └──[➖] format (71684:19)❌
  ├─┬webhook-pull-request-assigned
  │ └─┬pull_request
  │   ├─┬head
  │   │ └─┬repo
  │   │   └─┬id
  │   │     └──[➖] format (132232:31)❌
  │   └─┬base
  │     └─┬repo
  │       └─┬id
  │         └──[➖] format (131592:31)❌
  ├─┬webhook-pull-request-enqueued
  │ └─┬pull_request
  │   ├─┬head
  │   │ └─┬repo
  │   │   └─┬id
  │   │     └──[➖] format (141706:31)❌
  │   └─┬base
  │     └─┬repo
  │       └─┬id
  │         └──[➖] format (141070:31)❌
  ├─┬webhook-pull-request-auto-merge-disabled
  │ └─┬pull_request
  │   ├─┬head
  │   │ └─┬repo
  │   │   └─┬id
  │   │     └──[➖] format (134564:31)❌
  │   └─┬base
  │     └─┬repo
  │       └─┬id
  │         └──[➖] format (133928:31)❌
  ├─┬webhook-pull-request-review-request-removed
  │ ├─┬ONEOF
  │ │ └─┬pull_request
  │ │   ├─┬head
  │ │   │ └─┬repo
  │ │   │   └─┬id
  │ │   │     └──[➖] format (160247:33)❌
  │ │   └─┬base
  │ │     └─┬repo
  │ │       └─┬id
  │ │         └──[➖] format (159620:33)❌
  │ └─┬ONEOF
  │   └─┬pull_request
  │     ├─┬head
  │     │ └─┬repo
  │     │   └─┬id
  │     │     └──[➖] format (162654:33)❌
  │     └─┬base
  │       └─┬repo
  │         └─┬id
  │           └──[➖] format (162018:33)❌
  ├─┬project-card
  │ └─┬id
  │   └──[➖] format (75903:19)❌
  ├─┬webhook-team-edited
  │ └─┬repository
  │   └─┬id
  │     └──[➖] format (191032:23)❌
  ├─┬private-user
  │ └─┬id
  │   └──[➖] format (88773:19)❌
  ├─┬webhooks_pull_request_5
  │ ├─┬base
  │ │ └─┬repo
  │ │   └─┬id
  │ │     └──[➖] format (96301:27)❌
  │ └─┬head
  │   └─┬repo
  │     └─┬id
  │       └──[➖] format (96936:27)❌
  ├─┬repository
  │ └─┬id
  │   └──[➖] format (65234:19)❌
  ├─┬webhook-pull-request-unlabeled
  │ └─┬pull_request
  │   ├─┬base
  │   │ └─┬repo
  │   │   └─┬id
  │   │     └──[➖] format (181039:31)❌
  │   └─┬head
  │     └─┬repo
  │       └─┬id
  │         └──[➖] format (181679:31)❌
  ├─┬repository-invitation
  │ └─┬id
  │   └──[➖] format (79817:19)❌
  ├─┬key
  │ └─┬id
  │   └──[➖] format (89553:19)❌
  ├─┬webhook-pull-request-review-thread-resolved
  │ └─┬pull_request
  │   ├─┬head
  │   │ └─┬repo
  │   │   └─┬id
  │   │     └──[➖] format (172105:31)❌
  │   └─┬base
  │     └─┬repo
  │       └─┬id
  │         └──[➖] format (171526:31)❌
  ├─┬webhook-pull-request-auto-merge-enabled
  │ └─┬pull_request
  │   └─┬base
  │     └─┬repo
  │       └─┬id
  │         └──[➖] format (136261:31)❌
  ├─┬public-user
  │ └─┬id
  │   └──[➖] format (68595:19)❌
  ├─┬user-search-result-item
  │ └─┬id
  │   └──[➖] format (88647:19)❌
  ├─┬webhook-pull-request-review-comment-edited
  │ └─┬pull_request
  │   ├─┬base
  │   │ └─┬repo
  │   │   └─┬id
  │   │     └──[➖] format (152901:31)❌
  │   └─┬head
  │     └─┬repo
  │       └─┬id
  │         └──[➖] format (153528:31)❌
  ├─┬webhook-push
  │ └─┬repository
  │   └─┬id
  │     └──[➖] format (185564:23)❌
  ├─┬webhook-team-deleted
  │ └─┬repository
  │   └─┬id
  │     └──[➖] format (190479:23)❌
  ├─┬webhook-issues-opened
  │ └─┬changes
  │   └─┬old_repository
  │     └─┬id
  │       └──[➖] format (122278:27)❌
  ├─┬minimal-repository
  │ └─┬id
  │   └──[➖] format (69531:19)❌
  ├─┬webhook-pull-request-review-comment-created
  │ └─┬pull_request
  │   ├─┬head
  │   │ └─┬repo
  │   │   └─┬id
  │   │     └──[➖] format (149092:31)❌
  │   └─┬base
  │     └─┬repo
  │       └─┬id
  │         └──[➖] format (148465:31)❌
  ├─┬webhook-team-added-to-repository
  │ └─┬repository
  │   └─┬id
  │     └──[➖] format (189502:23)❌
  ├─┬codespace
  │ └─┬id
  │   └──[➖] format (71154:19)❌
  └─┬webhook-pull-request-review-comment-deleted
    └─┬pull_request
      ├─┬head
      │ └─┬repo
      │   └─┬id
      │     └──[➖] format (151314:31)❌
      └─┬base
        └─┬repo
          └─┬id
            └──[➖] format (150687:31)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 4             | 1                |
| components       | 100           | 99               |

Date: 07/03/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _100_ out of _104_
- **Modifications**: _2_
- **Removals**: _87_
- **Additions**: _15_
- **Breaking Removals**: _87_
- **Breaking Additions**: _12_

ERROR: breaking changes discovered