[GitHub] Update to 1.1.4-8a2dc25e1302b824ed48fe860969ca91 from 1.1.4-d543c2cfa43a2dcdc9526a6061319dd0 Detected Schema changes:
```
└─┬Paths
  ├─┬/repos/{owner}/{repo}/topics
  │ └─┬PUT
  │   └─┬Requestbody
  │     └─┬application/json
  │       └─┬Schema
  │         └─┬names
  │           └──[🔀] description (41464:32)
  └─┬/orgs/{org}/private-registries/{secret_name}
    └─┬PATCH
      └─┬Requestbody
        └─┬application/json
          ├──[➕] examples (13471:17)
          ├──[➖] examples (13466:17)❌
          └──[➕] examples (13466:17)

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 4             | 1                |

Date: 01/08/25 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _1_ out of _4_
- **Modifications**: _1_
- **Removals**: _1_
- **Additions**: _2_
- **Breaking Removals**: _1_

ERROR: breaking changes discovered