[GitHub] Update to 1.1.4 (hash: 4e919752833368e055ebb65f5999016b) from 1.1.4 (hash: 55aef53721fb2dc3fab1d254f1b5a0e5) Detected Schema changes:
├─┬Paths
│ └─┬/orgs/{org}
│   ├─┬GET
│   │ └─┬Responses
│   │   └─┬200
│   │     └─┬application/json
│   │       └─┬default-response
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         ├──[M] value (205715:9)
│   │         └──[-] value (205709:9)
│   └─┬PATCH
│     └─┬Responses
│       └─┬200
│         └─┬application/json
│           └─┬default
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             ├──[M] value (205715:9)
│             └──[-] value (205709:9)
└─┬Components
  ├─┬organization-full
  │ ├──[-] required (63945:9)❌
  │ └──[-] properties (63917:9)❌
  ├─┬team-organization
  │ ├──[-] required (67022:9)❌
  │ └──[-] properties (66994:9)❌
  ├─┬webhook-check-suite-rerequested
  │ └──[+] properties (84694:9)
  ├─┬webhook-check-suite-completed
  │ └──[+] properties (83461:9)
  ├─┬webhook-check-suite-requested
  │ └──[+] properties (84078:9)
  └─┬webhook-installation-target-renamed
    └─┬account
      └──[-] properties (93392:13)❌

Date: 07/07/23 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 112           | 0
components       | 8             | 5
❌ 5 Breaking changes out of 120

ERROR: breaking changes discovered