[GitHub] Update to 1.1.4-7c1a2eeb274057b6031d98c8b73d3185 from 1.1.4-3095567e16510823377396fa6baddc5a Detected Schema changes:
├─┬Paths
│ └──[-] path (21697:3)❌
└─┬Components
  ├──[-] examples (220701:7)❌
  └──[-] schemas (74876:7)❌

Date: 09/30/23 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 1             | 1
components       | 2             | 2
❌  3 Breaking changes out of 3
INFO: Removals: 3
INFO: Breaking Removals: 3

ERROR: breaking changes discovered