[GitHub] Update to 1.1.4-12cb03fcf4474304824f71a72f6d6238 from 1.1.4-27d2025567219eabd469390370e022c1 Detected Schema changes:
```
├─┬Paths
│ ├─┬/orgs/{org}/code-security/configurations/{configuration_id}
│ │ └─┬PATCH
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └──[➖] properties (6675:17)❌
│ └─┬/orgs/{org}/code-security/configurations
│   └─┬POST
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └──[➖] properties (6388:17)❌
└─┬Components
  ├─┬code-scanning-alert-rule-summary
  │ ├──[➖] properties (71404:9)❌
  │ ├──[➖] properties (71414:9)❌
  │ └──[➖] properties (71419:9)❌
  ├─┬code-scanning-alert-rule
  │ └─┬full_description
  │   └──[🔀] description (79649:24)
  └─┬code-security-configuration
    └──[➖] properties (71656:9)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| components       | 5             | 4                |
| paths            | 2             | 2                |

Date: 09/09/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _6_ out of _7_
- **Modifications**: _1_
- **Removals**: _6_
- **Breaking Removals**: _6_

ERROR: breaking changes discovered