[GitHub] Update to 1.1.4-9bdf0d87b61dcb75ec907d0344bd6b72 from 1.1.4-49b27bf070e71e6e97e24f657713d508 Detected Schema changes:
```
├─┬Paths
│ ├──[➖] path (13207:3)❌
│ ├──[➖] path (37743:3)❌
│ ├─┬/orgs/{org}/code-security/configurations
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         └──[🔀] value (201507:7)
│ │ └─┬POST
│ │   ├─┬Responses
│ │   │ └─┬201
│ │   │   └─┬application/json
│ │   │     └─┬default
│ │   │       ├──[🔀] value (201547:9)
│ │   │       ├──[🔀] value (201547:9)
│ │   │       ├──[🔀] value (201547:9)
│ │   │       ├──[🔀] value (201547:9)
│ │   │       ├──[🔀] value (201547:9)
│ │   │       ├──[🔀] value (201547:9)
│ │   │       ├──[🔀] value (201547:9)
│ │   │       ├──[🔀] value (201547:9)
│ │   │       ├──[🔀] value (201547:9)
│ │   │       ├──[🔀] value (201547:9)
│ │   │       ├──[🔀] value (201547:9)
│ │   │       ├──[🔀] value (201547:9)
│ │   │       ├──[➖] value (201770:9)
│ │   │       └──[➖] value (201770:9)
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         ├──[➖] properties (6307:17)❌
│ │         └──[➖] properties (6315:17)❌
│ ├─┬/orgs/{org}/properties/schema
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       ├─┬Schema
│ │ │       │ └─┬Schema
│ │ │       │   └──[🔀] $ref (72621:14)❌
│ │ │       └─┬default
│ │ │         └──[🔀] value (203565:7)
│ │ └─┬PATCH
│ │   ├─┬Responses
│ │   │ └─┬200
│ │   │   └─┬application/json
│ │   │     ├─┬Schema
│ │   │     │ └─┬Schema
│ │   │     │   └──[🔀] $ref (72621:14)❌
│ │   │     └─┬default
│ │   │       └──[🔀] value (203565:7)
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬properties
│ │           └─┬Schema
│ │             └──[🔀] $ref (72621:14)❌
│ ├─┬/orgs/{org}/code-security/configurations/{configuration_id}
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         ├──[🔀] value (201547:9)
│ │ │         ├──[🔀] value (201547:9)
│ │ │         ├──[🔀] value (201547:9)
│ │ │         ├──[🔀] value (201547:9)
│ │ │         ├──[🔀] value (201547:9)
│ │ │         ├──[🔀] value (201547:9)
│ │ │         ├──[🔀] value (201547:9)
│ │ │         ├──[🔀] value (201547:9)
│ │ │         ├──[🔀] value (201547:9)
│ │ │         ├──[🔀] value (201547:9)
│ │ │         ├──[🔀] value (201547:9)
│ │ │         ├──[🔀] value (201547:9)
│ │ │         ├──[➖] value (201770:9)
│ │ │         └──[➖] value (201770:9)
│ │ └─┬PATCH
│ │   ├─┬Responses
│ │   │ └─┬200
│ │   │   └─┬application/json
│ │   │     └─┬default
│ │   │       ├──[🔀] value (201610:9)
│ │   │       ├──[🔀] value (201610:9)
│ │   │       ├──[🔀] value (201610:9)
│ │   │       ├──[🔀] value (201610:9)
│ │   │       ├──[🔀] value (201610:9)
│ │   │       ├──[🔀] value (201610:9)
│ │   │       ├──[🔀] value (201610:9)
│ │   │       ├──[🔀] value (201610:9)
│ │   │       ├──[🔀] value (201610:9)
│ │   │       ├──[🔀] value (201610:9)
│ │   │       ├──[🔀] value (201610:9)
│ │   │       ├──[🔀] value (201610:9)
│ │   │       ├──[➖] value (201842:9)
│ │   │       └──[➖] value (201842:9)
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         ├──[➖] properties (6593:17)❌
│ │         └──[➖] properties (6600:17)❌
│ ├─┬/orgs/{org}/code-security/configurations/defaults
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (201567:7)
│ └─┬/orgs/{org}/properties/schema/{custom_property_name}
│   ├─┬GET
│   │ └─┬Responses
│   │   └─┬200
│   │     └─┬application/json
│   │       ├─┬Schema
│   │       │ └──[🔀] $ref (72621:14)❌
│   │       └─┬default
│   │         ├──[🔀] value (203581:9)
│   │         └──[➖] value (203819:9)
│   └─┬PUT
│     └─┬Responses
│       └─┬200
│         └─┬application/json
│           ├─┬Schema
│           │ └──[🔀] $ref (72621:14)❌
│           └─┬default
│             ├──[🔀] value (203581:9)
│             └──[➖] value (203819:9)
└─┬Components
  ├──[➖] examples (203799:7)❌
  ├──[➖] examples (203818:7)❌
  ├──[➕] examples (203580:7)
  ├──[➖] examples (216601:7)❌
  ├──[➕] examples (203564:7)
  ├──[➖] schemas (87541:7)❌
  ├──[➖] schemas (72808:7)❌
  ├──[➖] schemas (87537:7)❌
  ├──[➖] schemas (87530:7)❌
  ├──[➕] schemas (72621:7)
  ├─┬code-security-configuration
  │ ├──[➖] properties (71206:9)❌
  │ └──[➖] properties (71213:9)❌
  ├─┬webhook-custom-property-created
  │ └─┬definition
  │   └──[🔀] $ref (72621:14)❌
  └─┬webhook-custom-property-updated
    └─┬definition
      └──[🔀] $ref (72621:14)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 61            | 11               |
| components       | 14            | 11               |

Date: 08/14/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _22_ out of _75_
- **Modifications**: _49_
- **Removals**: _23_
- **Additions**: _3_
- **Breaking Removals**: _15_
- **Breaking Modifications**: _7_

ERROR: breaking changes discovered