[GitHub] Update to 1.1.4-5758ce6a93c789209abf3a01ab532091 from 1.1.4-4befd63c20b175c975d8d0d17534c658 Detected Schema changes:
```
└─┬Paths
  ├─┬/repos/{owner}/{repo}/code-scanning/codeql/databases/{language}
  │ ├──[➖] delete (24298:7)❌
  │ └─┬GET
  │   └──[🔀] description (24248:20)
  └─┬/repos/{owner}/{repo}/code-scanning/codeql/databases
    └─┬GET
      └──[🔀] description (24208:20)

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 3             | 1                |

Date: 10/31/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _1_ out of _3_
- **Modifications**: _2_
- **Removals**: _1_
- **Breaking Removals**: _1_

ERROR: breaking changes discovered