[GitHub] Update to 1.1.4-b74686f5a7ae762bfa3ad480e80383fb from 1.1.4-31be8bfdb65a495fdb443bd76a29b3a7 Detected Schema changes:
├─┬Paths
│ ├─┬/orgs/{org}/migrations
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬exclude
│ │           └──[M] description (8888:32)
│ └─┬/repos/{owner}/{repo}/environments/{environment_name}
│   └─┬PUT
│     └─┬Requestbody
│       └─┬application/json
│         ├─┬Schema
│         │ └──[-] properties (24768:17)❌
│         └─┬default
│           ├──[M] value (24795:19)
│           ├──[M] value (24795:19)
│           └──[-] value (24796:19)
└─┬Components
  ├──[-] schemas (77224:7)❌
  ├─┬webhook-check-suite-completed
  │ └─┬check_suite
  │   └─┬conclusion
  │     └──[M] description (87793:28)
  ├─┬code-scanning-default-setup
  │ └─┬languages
  │   └──[M] description (74685:24)
  ├─┬webhook-check-suite-requested
  │ └─┬check_suite
  │   └─┬conclusion
  │     └──[M] description (88407:28)
  ├─┬webhook-code-scanning-alert-closed-by-user
  │ └─┬alert
  │   └─┬dismissed_reason
  │     └──[M] description (89591:28)
  ├─┬webhook-deployment-status-created
  │ └─┬check_run
  │   └─┬conclusion
  │     └──[M] description (94905:28)
  ├─┬code-scanning-default-setup-update
  │ └─┬languages
  │   └──[M] description (74740:24)
  ├─┬webhook-code-scanning-alert-appeared-in-branch
  │ └─┬alert
  │   └─┬dismissed_reason
  │     └──[M] description (89333:28)
  ├─┬webhook-check-suite-rerequested
  │ └─┬check_suite
  │   └─┬conclusion
  │     └──[M] description (89014:28)
  ├─┬webhook-code-scanning-alert-fixed
  │ └─┬alert
  │   └─┬dismissed_reason
  │     └──[M] description (90098:28)
  └─┬full-repository
    └──[+] required (71584:9)❌

Date: 10/05/23 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 5             | 1
components       | 11            | 2
❌  3 Breaking changes out of 16
INFO: Modifications: 12
INFO: Removals: 3
INFO: Additions: 1
INFO: Breaking Removals: 2
INFO: Breaking Additions: 1

ERROR: breaking changes discovered