[GitHub] Update to 1.1.4-975ed3e1d762d10ff749fca3c2105b5a from 1.1.4-9cd6c8e7bead01c0c83af26875ff027b Detected Schema changes:
```
└─┬Components
  ├─┬code-scanning-alert-items
  │ └──[➖] properties (84623:9)❌
  ├─┬secret-scanning-alert
  │ └──[➖] properties (91942:9)❌
  ├─┬code-scanning-organization-alert-items
  │ └──[➖] properties (75545:9)❌
  ├─┬webhook-code-scanning-alert-created
  │ └─┬alert
  │   └──[➖] properties (108071:13)❌
  ├─┬webhook-code-scanning-alert-closed-by-user
  │ └─┬alert
  │   └──[➖] properties (107775:13)❌
  ├─┬code-scanning-alert
  │ └──[➖] properties (84732:9)❌
  └─┬organization-secret-scanning-alert
    └──[➖] properties (71914:9)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| components       | 7             | 7                |

Date: 02/12/25 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _7_ out of _7_
- **Removals**: _7_
- **Breaking Removals**: _7_

ERROR: breaking changes discovered