[GitHub] Update to 1.1.4-64034f0aaa76d6090b5eb70ffe778e12 from 1.1.4-a5a20c93e8ace47c79943304e911cf70 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit e2955c
                                                                                SPEC: extracted 2 commits from history

```
├─┬Paths
│ ├─┬/orgs/{org}/code-security/configurations/{configuration_id}
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         ├──[🔀] value (201396:9)
│ │ │         ├──[🔀] value (201396:9)
│ │ │         ├──[🔀] value (201396:9)
│ │ │         ├──[🔀] value (201396:9)
│ │ │         ├──[🔀] value (201396:9)
│ │ │         ├──[🔀] value (201396:9)
│ │ │         ├──[🔀] value (201396:9)
│ │ │         ├──[🔀] value (201396:9)
│ │ │         ├──[🔀] value (201396:9)
│ │ │         ├──[🔀] value (201396:9)
│ │ │         └──[➖] value (201491:9)
│ │ └─┬PATCH
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬enforcement
│ │           └──[🔀] description (6546:32)
│ ├─┬/orgs/{org}/code-security/configurations
│ │ └─┬POST
│ │   ├─┬Responses
│ │   │ └─┬201
│ │   │   └─┬application/json
│ │   │     └─┬default
│ │   │       ├──[🔀] value (201396:9)
│ │   │       ├──[🔀] value (201396:9)
│ │   │       ├──[🔀] value (201396:9)
│ │   │       ├──[🔀] value (201396:9)
│ │   │       ├──[🔀] value (201396:9)
│ │   │       ├──[🔀] value (201396:9)
│ │   │       ├──[🔀] value (201396:9)
│ │   │       ├──[🔀] value (201396:9)
│ │   │       ├──[🔀] value (201396:9)
│ │   │       ├──[🔀] value (201396:9)
│ │   │       └──[➖] value (201491:9)
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬enforcement
│ │           └──[🔀] description (6284:32)
│ └─┬/orgs/{org}/code-security/configurations/{configuration_id}/repositories
│   └─┬GET
│     └─┬Parameters
│       └──[🔀] description (6778:22)
└─┬Components
  ├──[➖] schemas (73561:7)❌
  ├─┬repository-rule-required-status-checks
  │ └─┬parameters
  │   └──[➖] properties (73739:13)❌
  ├─┬discussion
  │ └──[➖] properties (92188:9)❌
  ├─┬repository-rule
  │ ├──[➖] oneOf (74074:9)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (73520:14)❌
  │ ├─┬ONEOF
  │ │ ├──[🔀] title (73993:16)
  │ │ ├──[🔀] description (73994:22)
  │ │ ├─┬parameters
  │ │ │ ├──[➕] required (74016:15)❌
  │ │ │ ├──[➖] required (74172:15)❌
  │ │ │ ├──[➕] properties (74009:15)
  │ │ │ └──[➖] properties (74165:15)❌
  │ │ └─┬type
  │ │   ├──[➕] enum (74005:15)
  │ │   └──[➖] enum (74161:15)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (73726:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (73951:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (73760:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (73561:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (73550:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (73895:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (74064:9)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (73584:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (73595:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (73539:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (73652:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (74040:9)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (73681:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (73794:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (73509:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (73692:14)❌
  │ └─┬ONEOF
  │   └──[🔀] $ref (74017:9)❌
  ├─┬repository-rule-detailed
  │ ├──[➖] oneOf (86960:9)❌
  │ ├─┬ONEOF
  │ │ └─┬ALLOF
  │ │   └──[🔀] $ref (73828:14)❌
  │ ├─┬ONEOF
  │ │ ├─┬ALLOF
  │ │ │ └──[🔀] $ref (86812:14)❌
  │ │ └─┬ALLOF
  │ │   └──[🔀] $ref (73509:14)❌
  │ └─┬ONEOF
  │   └─┬ALLOF
  │     └──[🔀] $ref (73794:14)❌
  ├─┬repository-rule-workflows
  │ └─┬parameters
  │   └──[➖] properties (73985:13)❌
  └─┬label
    ├─┬default
    │ └──[➖] description (83887:24)
    ├─┬id
    │ └──[➖] description (83853:24)
    └─┬description
      └──[➖] description (83874:24)

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 25            | 0                |
| components       | 39            | 36               |

Date: 07/26/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _36_ out of _64_
- **Modifications**: _47_
- **Removals**: _14_
- **Additions**: _3_
- **Breaking Removals**: _9_
- **Breaking Modifications**: _22_
- **Breaking Additions**: _1_

ERROR: breaking changes discovered